Guardian Vendetta: 

7th Dec 2010
Andrew Brown's Guardian blog http://www.guardian.co.uk/commentisfree/andrewbrown/2010/dec/17/wikileaks-israel-shamir-russia-scandinavia begins: "WikiLeaks's spokesperson and conduit in Russia has been exposed in the Swedish media as an anti-semite and Holocaust denier..." The Swedish media source he cites is Expressen, which is part of a right-wing media group owned by the Jewish Bonnier family.

31st Jan 2011
A Guardian extract http://www.guardian.co.uk/media/2011/jan/31/wikileaks-holocaust-denier-handled-moscow-cables?INTCMP=SRCH from the Leigh/Harding book is titled: "Holocaust denier in charge of handling Moscow cables". The extract quotes “one staffer” and “one insider” - both of whom appear to be James Ball. It also describes “internal WikiLeaks documents, seen by the Guardian” without revealing Ball as the source.

5th Feb 2011
Writing in The Guardian, self-styled Web guru Evgeny Mozorov, pre-emptively declares Assange finished http://www.guardian.co.uk/media/2011/feb/07/age-wikileaks-style-vigilante-geek-over?INTCMP=SRCH . He throws in an obligatory Shamir reference, albeit fairly recognising him as “a stranger” to WikiLeaks.

16th Feb 2011
Assange contacts http://www.theoneclickgroup.co.uk/documents/ME-CFS_docs/Ian%20Hislop,%20Private%20Eye,%20No.%201283.pdf Private Eye magazine to complain about an article linking him with Shamir, including leaked emails suggesting Assange does not find Shamir’s writing anti-Semitic. Liberal Conspiracy, "the UK's most popular left-of-centre politics blog", gives a Hat Tip to James Ball for the story http://liberalconspiracy.org/2011/03/01/assange-goes-off-deep-end-blaming-jews-and-guardian-in-private-eye/ . Hmn, I wonder where Private Eye got those leaked emails?

NB: Private Eye, which was "frequently anti-Semitic" http://www.crikey.com.au/2011/03/02/eye-on-the-guardian-and-assange/ until the 1980s, is not always so concerned about anti-Semitism. http://www.indymedia.org.uk/en/2011/08/483153.html

24th Feb 2011
David Leigh tries to put the boot into Assange. In an article titled "It's Julian Assange's own 'tizzy' that bamboozles", http://www.guardian.co.uk/commentisfree/2011/feb/24/julian-assange-tizzy-important-work?INTCMP=SRCH he ridicules Assange's complaints, casts aspersions on his lawyers, and then (bizarrrely) lectures him about keeping his private life out of the media.

1st March 2011
A week after a judge rules that Assange should be extradited to Sweden, Private Eye's Ian Hislop opens fire in The Guardian http://www.guardian.co.uk/media/2011/mar/01/julian-assange-jewish-conspiracy-comments . Assange responds: "Hislop has distorted, invented or misremembered almost every significant claim and phrase. In particular, 'Jewish conspiracy' is completely false, in spirit and in word."

3rd March 2011
John Kampfner, CEO of Index on Censorship, cites Israel Shamir as his central reason for not supporting WikiLeaks. http://www.guardian.co.uk/commentisfree/2011/mar/03/julian-assange-big-picture?INTCMP=SRCH

9th April 2011
Esther Addley writes in The Guardian: "Douglas Murray, director of the centre for social cohesion, challenged Assange over the website's sources of funding, its staffing and connections with the Holocaust denier Israel Shamir, who has worked with the site."

2nd Sept 2011
A Guardian editorial http://www.guardian.co.uk/commentisfree/2011/sep/02/leader-wikileaks-unredacted-release?INTCMP=SRCH blames Assange for releasing the unredacted Cablegate files: "[WikiLeaks] has dwindled to being the vehicle of one flawed individual... occasionally brilliant, but increasingly volatile and erratic." There is no mention of David Leigh's password gaffe, nor of disgruntled ex-WikiLeaks staffer Daniel Domscheit-Berg, whose comments to German media triggered the public exposure of the files.

2nd Sept 2011
Former WikiLeaks insider James Ball writes: Why I Had To Leave WikiLeaks http://www.guardian.co.uk/media/2011/sep/02/why-i-had-to-leave-wikileaks . In this article, Ball cites Shamir as his reason for leaving WikiLeaks, although he also says "the last straw" was Assange's decision to publish the full, unredacted CableGate file (never mind it was his new editors at The Guardian who published the password). Ball also claims that he was worried that after the most important cables had been redacted, "a large volume of cables would remain, of little interest to any media organisation." And yet, when the unredacted cables were released, Ball took no further interest in them. He nonchalantly Tweeted that the media had “had their turn” with the cables, and it was the public's turn now.

18th Sept 2011
Nick Cohen goes to town with a disgusting smear piece in The Guardian: "The treachery of Julian Assange" http://www.guardian.co.uk/commentisfree/2011/sep/18/julian-assange-wikileaks-nick-cohen?INTCMP=SRCH . Cohen claims that the Shamir allegations render anything Assange ever says or does meaningless: "One can say with certainty, however, that Assange's involvement with Shamir is enough to discredit his claim that he published the documents in full because my colleagues on the Guardian inadvertently revealed a link to a site he was meant to have taken down."

26th Sept 2011
Ignoring basic media principles, David Leigh reviews the “unauthorised autobiography” of Assange: "It's a shame Assange couldn't get on with the Guardian... Assange shows, regrettably, that he is living in a fantasy world." http://www.guardian.co.uk/books/2011/sep/26/julian-assange-unauthorised-autobiography-review?INTCMP=SRCH

2nd Oct 2011
Karin Olsson, Culture Editor at Sweden's Expressen, is invited by a Guardian editor to write another substance-free smear piece: "Julian Assange: from hero to zero" http://www.guardian.co.uk/commentisfree/2011/nov/02/assange-hero-zero-swedes-pitiable?INTCMP=SRCH . She calls Assange “a paranoid chauvinist pig [who] cuts an increasingly pitiable figure”. As with the Nick Cohen article, this smear is widely reprinted in newspapers around the world, including Australia's Fairfax media. Once again, Assange's over-hyped association with Shamir is the central pillar of the attack. And as usual with these Guardian smear pieces, readers' comments are overwhelmingly disgusted at the author.

8th Nov 2011
James Ball wades back into the fray, ostensibly in protection of women's rights: Israel Shamir and Julian Assange's cult of machismo. http://www.guardian.co.uk/commentisfree/cifamerica/2011/nov/08/israel-shamir-julian-assange-cult-machismo?CMP=twt_gu  While slammming both men as misogynists, Ball repeats tired claims http://jaraparilla.blogspot.com/2011/10/where-now-wikileaks.html that Shamir gave unredacted US cables to the President of Belarus. Readers comments – including mine – are again overwhelmingly hostile to the author.

https://twitter.com/#!/davidleigh3/status/116526645640298496

https://twitter.com/#!/davidleigh3/status/112452902735462400

https://twitter.com/#!/davidleigh3/status/112088715928666114

http://www.guardian.co.uk/media/2011/sep/22/julian-assange-memoir-argument

https://twitter.com/#!/davidleigh3/status/109172400079380480 

Ball blames WL for Manning jail: 
http://www.guardian.co.uk/commentisfree/2011/jul/16/bradley-manning-wikileaks-security 

> But the reason Manning is now in military detention, awaiting court martial, perhaps ultimately lies in a smaller action still, an error thousands of email users make daily: choosing "cc" rather than "bcc".... Julian Assange boasts of "systems" in place to ensure he can have no idea as to the identity of a source. These – as these logs corroborate – are non-existent: Manning communicated directly with Assange... It is difficult to see who is protected by an arm's-length relationship with regular sources, other than WikiLeaks itself.


17/12/10, 4pm - Andrew Brown publishes blog with all source links still in Swedish language. Obviously a rush job as they didn't even bother to translate these sources. Brown even apologises for this at the end of the article. As well as smearing Israel Shamir it also seeks to smear his son, Johann Walstrom - Witness E in the Swedish case and a favourable witness for Assange - by association with his father.

17/12/10, 7pm - The Guardian writes 3 articles on the Belarus cables and 3 on the Cuba cables. It then uploads all its redacted Belarus and Cuba cables to Wikileaks. Some are very heavily - and apparently unnecessarily - redacted. Bear in mind that Israel Shamir was the first journalist to write about the Guardian "cable cooking".

17/12/10, 9pm - Nick Davies publishes the notorious "10 Days in Sweden" hit piece, which shamelessly distorted the leaked police protocol, kicking off the personal smear attacks against Assange in the English-speaking media.

Andrew Brown is the religious ("belief") editor at the Comment Is Free (CIF) section of Guardian. He lived in Sweden previously and still writes about it regularly. He invited Karin Olsson to write the Assange smear, as she admits here.

30 November 2011: Following Channel 4's "WikiLeaks: Secrets and Lies" smear-filled TV documentary, wikileaks.org published full details of the Guardian's involvement and producer's correspondence: http://www.wikileaks.org/Guardian-s-WikiLeaks-Secrets-and.html

A response from Shamir to James Ball: "A Portrait of the Petty Cheat as a Young Man"

"Cheats and thieves have to prove their moral superiority over their victims in order to justify their crimes. This is the case with a petty cheat and thief called James Ball. This young man was a hired hand in the Wikileaks; he was offered a bribe of a job by the Guardian and he gratefully accepted it, betraying Julian Assange's trust and stealing all he could put his sweaty hands on. Since then, he is obsessed with demeaning and debunking Assange: only moral disgrace of the Australian will reduce the burden of the traitor's guilt.

"One of his favourite routes is attacking Assange for associating with me, and today he did it again in the Guardian, responding to my recent piece Unmanning the Man. His arguments are repetitious, baseless and lame: I am called "anti-Semite", "H-denier" and "the man who gave the State Department secrets to Lukashenko" time and again.

"Shamir asked for access to all cable material concerning "the Jews", a request which was refused", says Ball. Oh no, James! That was before your switching sides, and you dutifully obliged. You did it even twice: *just before my departure you came to me on your own initiative and kindly handed me "a better file on Jews", twice as big as the previous one*. Apparently lying and cheating is your second nature by now."

More here: http://www.israelshamir.net/English/Ball.htm

*

Archived @wikileaks tweets to Jun 2011: https://wlcentral.org/twitter-archive

https://wlcentral.org/news

WL Timeline: https://defend.wikileaks.org/timeline/


Here is x7o's compendium of tweets dated up until the end of December, all of which are relevant to the Swedish investigation into Julian Assange: https://wlcentral.org/node/763 

== 2011

BILL KELLER Published: January 26, 2011 https://archive.ph/20120908021113/http://www.nytimes.com/2011/01/30/magazine/30Wikileaks-t.html#selection-323.2-331.27

The year 2011 began with Chelsea Manning in de facto solitary confinement at the US Marine Corps' Quantico Brig in Virginia, while Julian Assange was under house arrest at Ellingham Hall, the ten-bedroom country mansion of a friend and supporter, Vaughan Smith, in Norfolk, England. 

Smith, a former Army officer and war correspondent, link:https://www.thedailybeast.com/julian-assanges-guardian-angel-frontline-club-founder-vaughan-smith[bristled] at media hostility towards Assange.

> I have seen a human side of him that hasn’t been represented in the press. He is incredibly popular with my children, who see him as sort of an uncle figure. He’s somebody who will listen to you, and he’s somebody who will give you time and give you attention and help you... He’s damn good company.

Smith also ridiculed media claims that the much-vaunted "age of WikiLeaks" was already over.

> I think there are lots of bullies here. I think the British press have been bullying. I think the American government have been bullies. But it’s wider than that... Julian is presented as some sort of slightly nutty proponent of radical transparency. Actually, the truth is, he isn’t anything of the sort. 

> I think it would be foolish to determine WikiLeaks is over. It’s far too premature for that... I don’t think we’ve seen the end of Assange.

Assange's bail conditions included wearing an electronic ankle tag, reporting daily in person to the local police station, and observing a curfew between 10 pm and 8 am. Assange was frequently photographed by the media in the company of link:https://wikileaks.org/Profile-Sarah-Harrison.html[Sarah Harrison], who has modestly link:https://www.standard.co.uk/lifestyle/london-life/sarah-harrison-the-woman-behind-whistblowers-edward-snowden-and-julian-assange-a3342546.html[described herself] as "just a blonde girl" with "the most boring name ever”. Harrison had joined WikiLeaks to help with the Afghan War Diaries after previously working as an investigative researcher for The Bureau of Investigative Journalism and the Centre for Investigative Journalism. Rumours of a romantic relationship were quick to spread. 

=== January

On 6 January 2011 Vanity Fair link:https://www.vanityfair.com/news/2011/02/the-guardian-201102?currentPage=all%3Cbr%20/%3E[published] a lengthy but unreliable account of how WikiLeaks had worked with various media organisations in the previous year. "The Man Who Spilled The Secrets" article included a potted history of the Guardian and treated Guardian journalists, particularly editor-in-chief Alan Rusbridger, with an awed reverence. 

The first week of January 2011 also saw Bianca Jagger publish a link:https://www.huffpost.com/entry/the-julian-assange-trial_b_805299[rebuttal] of Nick Davies' link:https://www.huffpost.com/entry/post_1506_b_802680[rebuttal] of her link:https://www.huffpost.com/entry/trial-by-newspaper_b_800847[rebuttal] of his original Guardian article link:https://www.theguardian.com/media/2010/dec/17/julian-assange-sweden[Ten Days In Sweden], which had provided extensive details from the Swedish police file on the Assange case. Davies, who acknowledged having fallen out with Assange months earlier, had rejected Jagger's claims that his one-sided article, peppered with lurid sexual details, amounted to "trial by newspapers". 

Davies said the Swedish police file, which would normally have remained secret to guarantee a fair trail for all parties concerned, just "happened to make its way quite legitimately into the hands of somebody I have come across in the past". He refused to identify his source, who probably committed a crime by leaking the file, and finally washed his hands of responsibility for the article that bore his name: 

> The reality is that I didn’t write the story which the Guardian published. The copy which I filed was completely re-written in the Guardian office, a commonplace event in a newsroom.

Jagger dismissed Davies' ludicrous claim that he was defending his source just like WikiLeaks defended theirs, noting "there is a profound difference between exposing the deeds of powerful governments, corporations and the rich and throwing mud at those who released the information". She also made an important point which would have profound repercussions for years to come:

> Assange cannot defend himself at this point; all he can do is refute these allegations in the broadest terms. Davies knows that Assange’s lawyers will insist that he does not publicly engage in a rebuttal of the details in these allegations himself, when he is facing extradition and possible criminal charges. He is thoroughly disadvantaged by what Davies has done. 

Assange would never get his "day in court" to publicly refute the Swedish allegations. He would have to wait nearly seven more years before Swedish prosecutors even came to question him in London, as they routinely did in similar cases. And he would eventually learn that UK Crown Prosecutors had secretly link:https://www.theguardian.com/media/2018/feb/11/sweden-tried-to-drop-assange-extradition-in-2013-cps-emails-show[warned] their Swedish counterparts not to "get cold feet" and close the case (and then deleted their emails). Meanwhile, hostile media voices were free to say whatever they liked.

*

On 8 January 2011, while supporters of Assange and WikiLeaks organised more link:https://wlcentral.org/node/868[global protests], WikiLeaks link:http://twitter.com/#!/wikileaks/status/23591796542013441[launched] a new defense fund for Julian Assange, tweeting: "let us see Paypal try to close this one down too!"

On the same day, it was link:https://twitter.com/wikileaks/status/23604032362778625?s=20[revealed] that the US Department of Justice had issued Twitter with a court order, dated 14 December 2010 (link:https://web.archive.org/web/20110108131805/http://www.salon.com/news/opinion/glenn_greenwald/2011/01/07/twitter/subpoena.pdf[PDF]), for "all records" and "correspondence" relating to accounts "registered to or associated with WikiLeaks". These included Julian Assange and Bradley Manning, along with Iceland MP Birgitta Jónsdóttir, Tor developer Jacob Appelbaum, and Dutch hacker Rop Gonggrijp, who had helped work on the Collateral Murder video. 

Twitter advised affected users that they had ten days to oppose the request for information about their accounts.

> "I think I am being given a message, almost like someone breathing in a phone," link:https://web.archive.org/web/20110108092940/http://news.cnet.com/8301-31921_3-20027893-281.html[tweeted] Jónsdóttir.

The New York Times link:https://www.nytimes.com/2011/01/09/world/09wiki.html[reported] that this was "the first public evidence" of the criminal investigation ordered a month earlier by Obama's Attorney General Eric Holder, and said that the investigation would be "fraught with legal and political difficulties". Gonggrijp link:https://rop.gonggri.jp/?p=448[noted] that the affected users only found out about the order "because Twitter did the right thing and successfully fought for a second court order so they were able to tell us". Citing concerns for his young family, Gonggrijp later terminated his public support for WikiLeaks. 

The DoJ court order caused link:https://wlcentral.org/node/863[outrage] on Twitter, with @wikileaks warning that all 637,000 of their followers were now being targeted by the US government "under section 2.B" of the order. Enraged followers threatened a class action lawsuit against the US government. Others were intimidated into unfollowing @wikileaks, but within a week the account had a link:http://twitter.com/#!/wikileaks/status/25454900083171328[net gain] of 12,000 followers (hello again, Streisand Effect). Icelandic politicians voiced concerns that an MP colleague was being targeted and Foreign Minister Oessur Skarphedinsson link:http://www.dw-world.de/dw/article/0,,14758284,00.html[told German media] it was not acceptable that US authorities had demanded such information.

After some deliberation, Jacob Applebaum decided to push ahead with his planned return to the USA on 10 January, but organised for representatives from the American Civil Liberties Union (ACLU) to meet him at the airport. He then link:https://wlcentral.org/node/918[posted] a long series of tweets about the constant harrassment he received when traveling through US airports. 

> The CBP agents in Seattle were nicer than ones in Newark. None of them implied I would be raped in prison for the rest of my life this time.

*

On 11 January 2011 Julian Assange's routine case management hearing at Belmarsh Magistrates Court was swamped with media and supporters. The Guardian's link:https://www.theguardian.com/news/blog/2011/jan/11/wikileaks-latest-developments[live-blog] of the event included continuing global fallout from the US cable publications and highlights from a 35-page link:https://wlcentral.org/node/902[skeleton outline] of court arguments from Assange's lawyers.  

There were valid security concerns around Assange's court appearance, especially following the recent shooting of a US politician. WikiLeaks published a link:https://www.twitlonger.com/show/82g3kb[statement] condemning violent threats: 

> WikiLeaks staff and contributors have also been the target of unprecedented violent rhetoric by US prominent media personalities, including Sarah Palin, who urged the US administration to “Hunt down the WikiLeaks chief like the Taliban”. Prominent US politician Mike Huckabee called for the execution of WikiLeaks spokesman Julian Assange on his Fox News program last November, and Fox News commentator Bob Beckel, referring to Assange, publicly called for people to "illegally shoot the son of a bitch." US radio personality Rush Limbaugh has called for pressure to "Give [Fox News President Roger] Ailes the order and [then] there is no Assange, I'll guarantee you, and there will be no fingerprints on it.", while the Washington Times columnist Jeffery T. Kuhner titled his column “Assassinate Assange” captioned with a picture Julian Assange overlayed with a gun site, blood spatters, and “WANTED DEAD or ALIVE” with the alive crossed out.

> John Hawkins of Townhall.com has stated "If Julian Assange is shot in the head tomorrow or if his car is blown up when he turns the key, what message do you think that would send about releasing sensitive American data?"

> Christian Whiton in a Fox News opinion piece called for violence against WikiLeaks publishers and editors, saying the US should "designate WikiLeaks and its officers as enemy combatants, paving the way for non-judicial actions against them."

> WikiLeaks spokesman Julian Assange said: "No organisation anywhere in the world is a more devoted advocate of free speech than Wikileaks but when senior politicians and attention seeking media commentators call for specific individuals or groups of people to be killed they should be charged with incitement -- to murder. Those who call for an act of murder deserve as significant share of the guilt as those raising a gun to pull the trigger."

The web addresss julianassangemustdie.com, which was traced to a rightwing US blogger, was deleted soon afterwards. 

But the economic threats from US officials continued. On 12 January 2011 WikiLeaks link:https://www.wikileaks.org/WIKILEAKS-PRESS-RELEASE.html[responded] to Rep. Peter T. King's calls for a US embargo of WikiLeaks. 

> WikiLeaks today condemned calls from the chair of the House Committee on Homeland Security to "strangle the viability" of WikiLeaks by placing the publisher and its editor-in-chief, Julian Assange, on a US "enemies list" normally reserved for terrorists and dictators.

King specifically wanted to target Knopf, a New York publisher who had recently agreed to pay Assange for an autobiography. Assange said the book royalties would "keep Wikileaks afloat". An article in link:https://www.theatlantic.com/national/archive/2011/01/blacklisting-wikileaks/69535/[the Atlantic] ridiculed the madness of such a McCarthyist blacklist: "you could conceivably break the law merely by buying his book, or contributing to a WikiLeaks defense fund". 

WikiLeaks was under massive pressure but clearly not going down without a fight. In a 12 January link:https://www.newstatesman.com/blogs/the-staggers/2011/01/china-wikileaks-assange[interview] with John Pilger, Assange mentioned the existence of "insurance files": 

> "WikiLeaks is now mirrored on more than 2,000 websites... If something happens to me or to WikiLeaks, ‘insurance’ files will be released.... There are 504 US embassy cables on one broadcasting organisation and there are cables on Murdoch and News Corp.” 

Was it a bluff? In years to come, WikiLeaks would repeatedly post such encrypted "insurance files" online. This lead to a lot of wild speculation about the contents, and much of that speculation eventually solidified into misguided belief. Uninformed critics still angrily disclaim how WikiLeaks "promised" to post something but never did.  

*

15 January 2011 saw more link:https://wlcentral.org/node/947[global protests]. The rally in Sydney, Australia link:https://wlcentral.org/node/939[drew] around a thousand supporters. This followed another huge Sydney protest on 14 December 2010, with another one planned for 6 February 2011. WikiLeaks supporters around the world were energised, outraged, and working together to support their heroes. 

Such protests always featured prominent support for Chelsea Manning, who had now been jailed at the Quantico brig under torturous conditions for over five months. On 24 January, two Manning supporters (including regular visitor David House) were link:https://wlcentral.org/node/1063[turned away] from the facility after they attempted to deliver a petition of support with 42,000 signatures. On the following day, NBC reported that US military officials had placed Manning on suicide watch.  

> The official said that after Manning had allegedly failed to follow orders from his Marine guards, [Brig Commander James] Averhart declared Manning a "suicide risk." Manning was then placed on suicide watch, which meant he was confined to his cell, stripped of most of his clothing and deprived of his reading glasses — anything that Manning could use to harm himself.

Manning later claimed that the guards had created a scene by issuing conflicting demands such as "turn left, don't turn left". An investigation found that the Brig Commander had acted unlawfully, and he was replaced. Manning was removed from suicide watch on January 21 but remained on POI (Prevention Of Injury) status, despite repeated calls from Army health professionals for this to be lifted. Manning's lawyers filed a link:https://web.archive.org/web/20131202233021/http://www.armycourtmartialdefense.info/2011/01/article-138-complaint.html[complaint] explaining exactly what this POI status entailed: 

> Like suicide risk, he is held in solitary confinement. For 23 hours per day, he will sit in his cell. The guards will check on him every five minutes by asking him if he is okay. PFC Manning will be required to respond in some affirmative manner. At night, if the guards cannot see him clearly, because he has a blanket over his head or is curled up towards the wall, they will wake him in order to ensure that he is okay. He will receive each of his meals in his cell. He will not be allowed to have a pillow or sheets. He will not be allowed to have any personal items in his cell. He will only be allowed to have one book or one magazine at any given time to read. The book or magazine will be taken away from him at the end of the day before he goes to sleep. He will be prevented from exercising in his cell. If he attempts to do push-ups, sit-ups, or any other form of exercise he will be forced to stop. He will receive one hour of exercise outside of his cell daily. The guards will take him to an empty room and allow him to walk. He will usually just walk in figure eights around the room until his hour is complete. When he goes to sleep, he will be required to strip down to his underwear and surrender his clothing to the guards. 

On 24 January 2011 Amnesty International link:https://blog.amnestyusa.org/waronterror/inhumane-treatment-of-wikileaks-soldier-bradley-manning/[issued a call] for the USA to "alleviate the harsh pre-trial detention conditions of Bradley Manning." They link:https://www.amnestyusa.org/qa-wikileaks-and-freedom-of-expression/[ignored] pleas to show similar support for Julian Assange. 

> We are unaware of any legal action having yet been taken against Julian Assange for releasing the documents. As such, Amnesty International is not in a position to comment on any possible case against him specifically, as there are no charges to comment on. 

Amnesty also refused to comment on the Swedish allegations, arguing only that "due process should be followed". Their strange lack of interest in the Assange case was to endure many years, with only very occasional and limited mentions. 

*

The US government may not yet have charged Assange, but they already had a sealed indictment waiting for him, which meant they could file a charge whenever they chose to unseal the indictment. A 26 January 2011 email from Fred Burton, a Vice President at private intelligence firm Stratfor, link:https://wikileaks.org/gifiles/docs/13/1352579_fw-ct-assange-manning-link-not-key-to-wikileaks-case-.html[stated]:

> Not for Pub --

> We have a sealed indictment on Assange.

> Pls protect

Fred Burton was Stratfor's Vice-President for Counterterrorism and Corporate Security, and a former Deputy Chief of the Department of State's counterterrorism division for the Diplomatic Security Service. Stratfor's business model relies on close communication with US intelligence agencies, and many Stratfor staff are former CIA agents. Burton's email was not uninformed gossip - Assange’s own lawyers had already warned of a possible indictment - but it remained secret until February 2012, when WikiLeaks link:https://wikileaks.org/Stratfor-Emails-US-Has-Issued.html[released] the link:http://wikileaks.org/the-gifiles.html[Global Intelligence files]. 

Despite such evidence of a US indictment, media commentators and senior government officials in Britain, Australia, and Sweden - many of whom must have known about the sealed indictment - continued to pretend that Assange's fears of extradition to the USA were entirely baseless. 

In August 2012, Reuters falsely link:https://uk.reuters.com/article/us-wikileaks-assange-usa/despite-assange-claims-u-s-has-no-current-case-against-him-idUSBRE87L12W20120822[reported] that the USA had "no current case" against Assange and State Department spokeswoman Victoria Nuland dismissed his extradition concerns as "wild assertions". 

> “He is clearly trying to deflect attention away from the real issue,” Nuland said.

In November 2013 the Washington Post went even further, falsely link:https://web.archive.org/web/20131121011138/https://www.washingtonpost.com/world/national-security/assange-not-under-sealed-indictment-us-officials-say/2013/11/18/8a3cb2da-506c-11e3-a7f0-b790929232e1_story.html[reporting] that Assange was "not under sealed indictment" based on comments from anonymous US officials. 

> “We will treat this news with skepticism,” said WikiLeaks spokesman Kristinn Hrafnsson. “Unfortunately, the U.S. government has a track record of being deceptive.”

*

Also on 26 January 2011, the New York Times' executive editor Bill Keller published a link:https://wlcentral.org/node/1126[ridiculously long] article about his dealings with WikiLeaks during the previous year. Keller was intent on establishing his own narrative of events, thus insulating his newspaper from allegations of irresponsible reporting, but he also provided qualified support for Assange and WikiLeaks in the face of US government threats:

> But while I do not regard Assange as a partner, and I would hesitate to describe what WikiLeaks does as journalism, it is chilling to contemplate the possible government prosecution of WikiLeaks for making secrets public, let alone the passage of new laws to punish the dissemination of classified information, as some have advocated. Taking legal recourse against a government official who violates his trust by divulging secrets he is sworn to protect is one thing. But criminalizing the publication of such secrets by someone who has no official obligation seems to me to run up against the First Amendment and the best traditions of this country.

Five days later, 60 Minutes aired a lengthy link:http://is.gd/7Ll9ZM[interview] with Assange were he claimed "our founding values are those of the U.S. revolution".

> 60 Mins: Someone in the Australian government said that, “Look, if you play outside the rules you can’t expect to be protected by the rules.” And you played outside the rules. You’ve played outside the United States’ rules.

> Assange: No. We’ve actually played inside the rules. We didn’t go out to get the material. We operated just like any U.S. publisher operates. We didn’t play outside the rules. We played inside the rules.

> 60 Mins: There’s a special set of rules in the United States for disclosing classified information. There is longstanding -

> Assange: There’s a special set of rules for soldiers. For members of the State Department, who are disclosing classified information. There’s not a special set of rules for publishers to disclose classified information. There is the First Amendment. It covers the case. And there’s been no precedent that I’m aware of in the past 50 years of prosecuting a publisher for espionage. It is just not done. Those are the rules. You do not do it.

Assange insisted that WikiLeaks's 2010 releases would in fact be "encouragement to every other publisher to publish fearlessly."

> If we’re talking about creating threats to small publishers to stop them publishing, the U.S. has lost its way. It has abrogated its founding traditions. It has thrown the First Amendment in the bin. Because publishers must be free to publish.

*

Meanwhile, the world was in turmoil. Tunisia's president Zine al-Abidine Ben Ali link:https://www.theguardian.com/world/2011/jan/14/tunisian-president-flees-country-protests[fled his country] in mid-January 2011 - despite winning 89% of the vote two years earlier - and became the first dictator to fall in what became known as the Arab Spring. The widespread protests were at least partly triggered by WikiLeaks' Cablegate publications, which provided hard proof of endemic corruption across the Middle East. 

The final days of January saw huge protests in Egypt, with US-backed dictator Hosni Mubarak repeatedly shutting down Internet access to stem the flow of information. On 29 January activists began link:http://twitter.com/#!/wikileaks/status/31046777343836160[faxing] WikiLeaks cables into Egypt to bypass the Internet blockade. Mubarak resigned less than two weeks later. 

Critics accused Assange of trying to take full credit for these revolutions, although he did no such thing. On 30 January 2011 @wikileaks link:https://twitter.com/wikileaks/status/31448923629420544?s=20[tweeted]:

> Yes, we may have helped Tunisia, Egypt. But let us not forget the elephant in the room: Al Jazeera + sat dishes

The Arab Spring also saw many online activists joining the #Anonymous global collective to bring down government websites with massive Denial of Service (DDos) attacks. Western analysts could hardly complain when such activists helped bring down authoritarian governments in the Middle East, but it was a different story for those who had targetted US and British websites in the previous year. On 28 January the FBI link:https://archives.fbi.gov/archives/news/pressrel/press-releases/warrants_012711[announced] that it had executed over forty search warrants in response to DDoS attacks, while five people were link:https://wlcentral.org/node/1104[arrested] in the United Kingdom. 

Anons reacted to these arrests by publishing an link:https://www.indymedia.org.uk/en/2011/01/472905.html[open letter] to the UK government, ridiculing the harsh penalties (maximum 10 years imprisonment and a fine of up to £5000) for a crime that temporarily brought down websites but left no permament damage. 

> The fact that thousands of people from all over the world felt the need to participate in these attacks on organisations targeting Wikileaks and treating it as a public threat, rather than a common good, should be something that sets you thinking. You can easily arrest individuals, but you cannot arrest an ideology. 

=== February

On the first day of February 2011 Guardian editor David Leigh and Guardian journalist Luke Harding published a book titled link:https://www.amazon.co.uk/WikiLeaks-Inside-Julian-Assanges-Secrecy/dp/0852652399[WikiLeaks: Inside Julian Assange’s War on Secrecy]. The book was rushed into print to maximise profits from the recent leaks, but it was not the first published WikiLeaks book. A book in German was published in January 2011, while link:http://www.blurb.com/bookstore/detail/1949679[The Age of WikiLeaks] was published by veteran US journalist Greg Mitchell on 29 January 2011. 

But the book by Leigh and Harding, with an introduction by Guardian Editor-in-chief Alan Rusbridger, had the most impact, not only because Hollywood later bought the movie rights, but because it contained a chapter with the subheading: 

> "ACollectionOfDiplomaticHistorySince_1966_ToThe_PresentDay#". 

This, as the book revealed, was the secret password to a huge encypted file which contained all the Cablegate data. Assange had entrusted the password to Leigh in 2010 so that the Guardian editor could browse the data and cherry-pick the stories the Guardian wanted to cover. 

What Leigh did not know was that a copy of the full Cablegate archive still existed "in the wild" on the Internet. Now that Leigh had published the password, anyone who knew the location of the file could access the full unredacted contents. Fortunately, only a few people knew the location. Unfortunately, one of those people was Daniel Domscheit-Berg. 




* 

14 Feb 2001 by Julian Borger and James Ball: WikiLeaks cables: Egyptian military head is 'old and resistant to change' https://www.theguardian.com/world/2011/feb/14/wikileaks-cables-egyptian-military-head just one cable

> US ambassador to Cairo gives his opinion on Muhammad Tantawi and number two general, Sami Enan

15 Feb 2011 DDB published English version of his book link:https://www.amazon.co.uk/Inside-WikiLeaks-Assange-Dangerous-Website/dp/0224094017[Inside WikiLeaks: My Time with Julian Assange at the World's Most Dangerous Website]. 

link:https://www.spiegel.de/international/world/new-book-from-assange-s-deputy-the-difficult-partnership-of-wikileaks-leadership-duo-a-744718.html[Der Spiegel] was not impressed, saying it " feels more like the story of a spurned lover than an important historical account."

> The 305-page book has been ghost written by Tina Klopp, a young editor at the website of the German weekly newspaper Die Zeit.

and: 

> But even after reading the book it remains a mystery as to why Assange came to distrust Domscheit-Berg. The author appears not to know the answer himself.

23 Feb 2011 by James Ball: WikiLeaks cables: UK blocked $60m arms deal over fears of Iran link https://www.theguardian.com/world/2011/feb/23/wikileaks-cables-arms-deal-swaziland just one cable from James here

> Cables spell out possible destinations if deal between UK arms broker and Swaziland had gone ahead

* 

MARCH 2011

Leigh tweet ridiculed

https://www.crikey.com.au/2011/03/16/media-briefs-guardian-v-wikileaks-nines-nuclear-map-hoax-fairfax-sued-for-one-billion-dollars/


APRIL

7 April Leigh and Ball: Latest WikiLeaks cables reveal Israel's fears and alliances https://www.theguardian.com/world/2011/apr/07/israeli-wikileaks-cables-julian-assange 

> The revelations come in a tranche of the most militarily sensitive cables from the US embassy in Tel Aviv. They have been handed over to Israeli newspapers by WikiLeaks founder Julian Assange. The Hebrew-language paper Yediot this week announced a deal under which it will print an interview with Assange, who has recently had to defend WikiLeaks from accusations of antisemitism.


MAY 

Gitmo files see image 2011mayjamesballgitmo.png

3 May James Ball US troops were yards from Osama bin Laden house in 2008 – WikiLeaks files https://www.theguardian.com/media/2011/may/03/us-bin-laden-hideout 

> US forces were stationed just a few hundred yards from Osama Bin Laden's Abbottabad compound in October 2008, according to reports within the WikiLeaks embassy cables. The revelation that US forces were so close to the world's most wanted man in 2008 comes after material from the Guantánamo files suggested the US may have received the intelligence that led them to Bin Laden as early as 2008.

12 May WikiLeaks, get out of the gagging game by James Ball https://www.theguardian.com/commentisfree/2011/may/12/wikileaks-confidentiality-agreement-julian-assange 

> Yesterday, media lawyer and legal blogger David Allen Green published the full text of the gagging order signed by almost all WikiLeaks employees earlier this year... WikiLeaks staffers face a £12m penalty if they reveal any information about WikiLeaks' day-to-day operations, let alone any documents given to the whistleblowing organisation. In a move reminiscent of the UK's reviled superinjunctions, even revealing the existence of the gagging order is itself a breach.

> Within minutes of the publication of the gagging document, WikiLeaks supporter Asher Wolf pointed out to her followers that I, during my time with the organisation, had refused to sign the document. Others quickly pointed out the leaked document was unsigned. Yes, it was my copy of the agreement that was published. The leak was hardly premeditated though – it emerged through the refusal of transparency campaigner Heather Brooke to believe I was not joking when discussing the terms of the WikiLeaks contract. Inadvertently, I sent her a photograph of a portion of the document publicly rather than privately, over Twitter. Needless to say, this provoked a lot of interest, and one thing then led to another. 

> It was January this year, and around 10 WikiLeaks staff and volunteers were working from Norfolk, where Julian Assange is confined thanks to his legal travails. Julian arrived with a copy of this document for everyone in the room, and asked all to sign it there and then, to demonstrate to all present they were trustworthy and decent. Unlike everyone else present – who were largely young activists with little or no professional training – I read the document first. In addition to the aforementioned concerns, the document was backdated – in my case by seven months. I had given dozens of print and TV interviews, at Julian's instruction, often covering small behind-the-scenes snippets. Could this document now be used retrospectively to mount a legal challenge should Julian ever so wish? It could. I refused to sign, and listed several reasons why. At this point, more than one person in the room asked for their copy of the agreement back. This was refused. Julian then proceeded to spend two hours – shouting – explaining why I must sign the document, or else risk the lives and wellbeing of everyone in the room, and never be trusted again. Eventually, he departed. The rest of the day, and long into the night, was spent with other WikiLeakers begging, reasoning, or cajoling me into signing the document. I later learned Julian had specifically requested they use every possible effort to "apply psychological pressure" until I signed. Next morning the conversation resumed in private. In far more measured terms than the previous day, Julian acknowledged no one but him was in any personal danger. He said as I had already given notice I'd be leaving the organisation, surely I could understand that WikiLeaks would need "something to use against you" should I prove unreliable. At one point, getting nowhere, he even referred to the need to protect his intellectual rights in case it damage the profitability of his book.
* 

Newsweek published an link:[https://www.newsweek.com/wikileaks-too-full-itself-217216[article] with input from a WikiLeaks insider: 

> A person in close contact with other WikiLeaks activists around Europe, who asked for anonymity when discussing a sensitive topic, says that man of them were privately concerned that Assange has continued to spread allegations of dirty tricks and hint at conspiracies against him without justification. Insiders say that some people affiliated with the website are already brainstorming whether there might be some way to persuade their front man to step aside, or failing that, even to oust him. 

Assange thought DDB was the culprit and confronted him. Wired magazine link:https://www.wired.com/2010/09/wikileaks-revolt/[published "purported" excerpts] from the conversation. Wired said "At least half a dozen WikiLeaks staffers have tendered their resignations in recent weeks". TRUE? 

25-year-old Herbert Snorrason, an Icelandic university student who until recently helped manage WikiLeaks' secure chat room, said: 

> "We found out that the level of redactions performed on the Afghanistan documents was not sufficient. I announced that if the next batch did not receive full attention, I would not be willing to cooperate."

WHAT DOES THAT MEAN? 

> Tension has been mounting within WikiLeaks since July, when the organization went public with a U.S. Army database of 92,000 documents from the war in Afghanistan. WikiLeaks released 77,000 of the documents, temporarily holding back 15,000 records to redact the names of Afghan informants who might be at risk of Taliban reprisal. Despite the precaution, the names of some Afghan collaborators slipped out in the 77,000 records, earning WikiLeaks criticism from human rights organizations and the international free press group Reporters Without Borders, as well as the Pentagon. There has been no evidence to date, however, that anyone has suffered actual harm due to the documents.

The redaction of the final 15,000 documents was completed weeks ago, according to some former WikiLeaks staffers, but Assange has held off on publishing those reports for reasons he has not shared within the group.

Snorrason said Assange told him: 

> I am the heart and soul of this organization, its founder, philosopher, spokesperson, original coder, organizer, financier and all the rest. If you have a problem with me, piss off.

Domscheit-Berg announced his resignation in an interview with link:http://www.spiegel.de/international/germany/0,1518,719561,00.html[Der Spiegel]. By then, a key WikiLeaks programmer had resigned as well, sources say. The coder was responsible for building the software tool WikiLeaks' volunteers were using to perform a painstaking, line-by-line harm-minimization review of the Iraq logs.

Then Snorrason, the Icelandic university student, resigned after he challenged Assange on his decision to suspend Domscheit-Berg and was bluntly rebuked.

> Assange: I am investigation a serious security breach. Are you refusing to answer?

Domscheit-Berg: i am investigating a serious breach in trust. are you refusing to answer?

Assange: No you are not. I initiated this conversation. Answer the question please.

Domscheit-Berg: i initiated it

Domscheit-Berg: if you look above

Domscheit-Berg: twice already

Domscheit-Berg: i want to know what the agreements are in respect to iraq

Assange: That is a procedural issue. Don't play games with me.

Domscheit-Berg: stop shooting at messengers

Assange: I've had it.

Domscheit-Berg: likewise, and that doesnt go just for me

Assange: If you do not answer the question, you will be removed.

Domscheit-Berg: you are not anyones king or god

Domscheit-Berg: and you're not even fulfilling your role as a leader right now

Domscheit-Berg: a leader communicates and cultivates trust in himself

Domscheit-Berg: you are doing the exact opposite

Domscheit-Berg: you behave like some kind of emporer or slave trader

Assange: You are suspended for one month, effective immediately.

Domscheit-Berg: haha

Domscheit-Berg: right

Domscheit-Berg: because of what?

Domscheit-Berg: and who even says that?

Domscheit-Berg: you? another adhoc decision?

Assange: If you wish to appeal, you will be heard on Tuesday.

*

JULY 

11 July by James Ball and Charles Archer Anonymous threatens police over phone hacking and Julian Assange  https://www.theguardian.com/technology/2011/jul/11/anonymous-police-phone-hacking-julian-assange 

> Senior source inside hacker collective seeks to embarrass Metropolitan police and judges with 'explosive' revelations... The collective is understood to be seeking to express anger over News International's phone hacking and at the threatened extradition of WikiLeaks founder Julian Assange. A Twitter feed purporting to belong to Sabu, a senior figure within the group and the founder of the spin-off group LulzSec, which hacked a site linked to the CIA and the UK's Serious Organised Crime Agency, promised two releases of information would be launched within a day. "Everyone brace," he tweeted. "This will be literally explosive." A follow-up message read: "ATTN Intelligence community: Your contractors have failed you. Tomorrow is the beginning." ... Last Wednesday, two days after the Dowler revelations, a listing of emails of NoW staff appeared on Pastebin.

The account: @anonymouSabu

27 July 2011: LulzSec hacking suspect 'Topiary' arrested https://www.theguardian.com/technology/2011/jul/27/lulzsec-hacking-suspect-topiary-arrested 

> Police arrest 18-year-old man in Shetland Islands who is alleged to be involved in hacker attacks on law enforcement agencies ... The arrest of Topiary is the third made in the UK in the search for members of the group, following that of Ryan Cleary, in Essex, in June, and the arrest and release in London last week of a 16-year-old known online as Tflow. The apparent ringleader of the group, known online as Sabu, remains at large.

> LulzSec claims to have carried out attacks on a number of sites, including the Sun last week when it redirected readers to a fake story claiming Rupert Murdoch was dead, and others during May and June including attacks on the UK's Serious Organised Crime Agency, an FBI-affiliated site, the US Congress, and Sony's European network. "Topiary" was on Wednesday being transported to London for interview. The main Twitter account connected to LulzSec, which has more than 340,000 followers and which Topiary is alleged to control, fell silent shortly before midday on Wednesday. Topiary's own twitter feed, @atopiary, was wiped clear on Friday, save for one tweet reading: "You cannot arrest an idea." Police in the UK and US have been rounding up suspected members of LulzSec, and those who in January participated in attacks on the payments site PayPal as part of the Anonymous hacking collective. Last week the FBI made 16 arrests of alleged participants in the attacks, and it is believed to have a list of 1,000 computer addresses it is targeting. On Wednesday members of Anonymous and LulzSec staged a peaceful protest against PayPal for its refusal to allow payments to WikiLeaks by closing their PayPal accounts.

AUGUST

21 August DDB in Der Spiegel: http://translate.google.com/translate?act=url&hl=en&ie=UTF8&prev=_t&rurl=translate.google.com&sl=auto&tl=en&twu=1&u=http://www.spiegel.de/netzwelt/netzpolitik/0,1518,781458,00.html

Sat Aug 20 - Statement by Julian Assange on the reported destruction of WikiLeaks source material by Daniel Domscheit-Berg http://www.twitlonger.com/show/chdoeo


BBC 
22 August 2011:Ex-Wikileaks man 'deleted files' https://web.archive.org/web/20110901180200/http://www.bbc.co.uk/news/technology-14616899 

August: http://www.twitlonger.com/show/chek37

> WikiLeaks (@wikileaks)

Posted Sunday 21st August 2011 from Twitlonger

WikiLeaks Statement on Daniel Domscheit-Berg and OpenLeaks

Sat Aug 20 23:41:31 2011 GMT

Five days short of a year ago, on 25 August 2010, WikiLeaks suspended former employee "Daniel Domscheit-Berg". Over the last 11 months, we have tried to negotiate the return of various materials taken by Mr. Domscheit-Berg, including internal communications and over 3000 unpublished, private whistleblower communications to WikiLeaks. Mr. Domscheit-Berg has repeatedly attempted to blackmail WikiLeaks by threatening to make available, to forces that oppose WikiLeaks, these private communications and to which Mr. Domscheit-Berg is not a party. He has stated he will commit this action, should WikiLeaks move to charge him with sabotage or theft. Mr. Domscheit-Berg has refused to return the various materials he has stolen, saying he needs them, solely, to carry out this threat. Mr. Domscheit-Berg has already, secretly, and with malicious intent, disclosed portions of the private communications content to other parties, to the harm of WikiLeaks.

The negotiations have now been terminated by the mediator, Andy Müller-Maguhn, who has stated that he doubts Mr. Domscheit-Berg's integrity and claimed willingness to return the material and that under those circumstances Müller-Maguhn cannot meaningfully continue to mediate. In response, Mr. Domscheit-Berg has stated that he has, or is about to, destroy thousands of unpublished whistleblowers disclosures sent to WikiLeaks. The material is irreplaceable and includes substantial information on many issues of public importance, human rights abuses, mass telecommunications interception, banking and the planning of dozens of neo-nazi groups. Our sources have in some cases risked their lives or freedom attempting to convey these disclosures to WikiLeaks and to the public.

As a matter of policy and implementation WikiLeaks does not collect or retain source identifying information, so fortunately, source identities for this material are not significantly at risk.

WikiLeaks has only made one prior formal statement regarding Mr. Domscheit-Berg, which we issued in February and repeat here:

WikiLeaks has been taking legal action against former employee, Daniel Domscheit-Berg who was suspended from the organization in September. The reasons for these actions will gradually become clear, but some are hinted at by extracts from Domscheit-Berg's book.
In the book Domscheit-Berg confesses to various acts of sabotage against the organization. The former WikiLeaks staffer admits to having damaged the sites primary submission system and stolen material.
The sabotage and concern over motives led to an overhaul of the entire submission system, an ongoing project that is not being expedited due to its complex nature and the organization´s need to focus its resources on publication and defense.
It should be noted that Domscheit-Berg´s roles within WikiLeaks were limited and started to diminish almost a year ago as his integrity and stability were questioned. He has falsely misrepresented himself in the press as a programmer, computer-scientist, security expert, architect, editor, founder, director and spokesman. He is not a founder or co-founder and nor was there any contact with him during the founding years. He did not even have an email address with the organization until 2008 (we launched in December 2006). He cannot program and wrote not a single program for the organization, at any time.
Domscheit-Berg was never an architect for the organization, technically, or in matters of policy. He was a spokesperson for WikiLeaks in Germany at various times, but he was never the spokesman for WikiLeaks, nor was he ever WikiLeaks editor, although he subedited some articles. He was also never a computer scientist, or computer security expert, although he was a computer science student many years ago. His accounts of the crucial times in WikiLeaks history since April last year are therefore based upon limited information or malicious falsifications.

In order to provide an environment which would encourage Mr. Domscheit-Berg to return what he has stolen and not to use it for malicious purposes, we have made no further statements until today.

This diplomatic silence has been difficult for us, and, is perhaps a warning lesson about secret diplomacy. While we have been silent in order to maximize the chances of regaining the material that was entrusted to us, Mr. Domscheit-Berg has issued dozens of legally harmful falsehoods including during our ongoing legal conflict with the Pentagon, during the imprisonment and investigation of two alleged sources, Bradley Manning and Rudolf Elmer and during the imprisonment and extradition hearings of our founder Julian Assange.

Mr. Manning is imprisoned pending trial, Mr. Assange is under house arrest pending extradition. Over 100 WikiLeaks supporters have been arrested or raided by the FBI, Scotland Yard and other police or intelligence services. Publicly declared task forces into WikiLeaks over the last year include the Pentagon (120 personnel), the State Department, the FBI, the US Department of Justice and the CIA. Concurrently, a "secret" Grand Jury in Washington (Alexandria) has been considering whether to indict Julian Assange with espionage as a result of Wikileaks' publishing.

Mr. Domscheit-Berg has acted dishonestly, he has admitted to stealing WikiLeaks property, and has admitted to the deliberate sabotage of Wikileaks’ operations, impeding it from carrying out the will of its sources. He has lied, constantly, and flagrantly, to the public, to us, to our lawyers, and to the mediator, Andy Müller-Maguhn.

We are making this public statement in a final attempt to make Mr. Domscheit-Berg return the data he has stolen, before he destroys it. This material was entrusted to WikiLeaks specifically by our sources, who often go to significant risks to bring us materials under the basis that we will bring their revelations to the public and defend them from censorship. Every day that passes compromises the will of these sources and the efforts they have undertaken.

Mr. Domscheit-Berg has illegitimately taken this data along with Wikileaks’ secure online submissions system, funds and internal documentation. He has sabotaged years of work, none of which was his own. We have had to recreate this work under difficult circumstances. This rebuilding comes at a significant cost to Wikileaks, which is under an unlawful Washington instigated financial blockade enforced by the big US financial companies. This cost is ultimately borne by the public, who fight to keep our operations afloat with contributions of twenty dollars a month or less.

Statement by Julian Assange Sat Aug 20 20:21:04 2011 UTC

WikiLeaks does not record or retain source identifying information, however the claimed destruction of documents entrusted to WikiLeaks between January 2010 and August 2010 demands the revelation of inside information so sources can make their own risk assessments.

Early in 2010, Daniel Domscheit-Berg, (then "Daniel Berg", "Daniel Schmitt") (born 1978), who was responsible for keeping selected WikiLeaks backups, met and entered into a relationship with Anke Domscheit-Berg (then, "Anke Domscheit") (born 1968) who described her job title as "Director Government Relations" for Microsoft, Germany.

DDB told me that ADB's role was to interface with the German government on behalf of Microsoft. He was proud that he had been to a party at the German ministry of the interior, as ADB's consort, and that ADB was on intimate terms with senior figures in the German government and bureaucracy.

DDB told me that he had moved into ADBs house in Berlin, without any counter-intelligence cover, going so far as to place his legal name on a street visible mail box and the interior door and that he would work from this location.

At this point WikiLeaks issued a policy directive that DDB not be permitted contact with source material.

ADB and DDB officially married within a few weeks and changed their surnames to "Domscheit-Berg".

DDB secretly, and in clear violation of WikiLeaks internal security directives, recorded internal WikiLeaks encrypted "chat" conversations. He initially publicly denied having done so, but attempted to place many of these recordings into his ghostwritten book, most of which were rejected by his publishers' lawyers as violations of german privacy law. Others he secretly conveyed to hostile media, such as Wired magazine, which had been involved in the arrest and persecution of US intelligence analyst Bradley Manning.

His book, "Inside WikiLeaks", contains many proven malicious libels and breaches of WikiLeaks security policies. The book is promoted throughout U.S. military book stores, by the U.S. military.

After DDB's suspension in August 2010, he managed, through guile, to convince a German WikiLeaks system administrator, who was an old associate of DDB's, to obtain the keys and data for a large quantity of then pending WikiLeaks whistleblower disclosures.

In the last year there has been publicly declared task forces or investigations into WikiLeaks by the CIA, the Pentagon, the FBI, the Department of State, the DoJ, ASIO, ASIS, and the AFP (the last has now been publicly cancelled, finding that no Australian laws have been broken). Many other agencies, such as the NSA have also been involved, but not publicly declared.

I have received a warning from a current Western intelligence officer that DDB has been in contact with the FBI, on more than one occasion, and that the information from this contact was "helpful". I do not know if DDB was complicit with the reported contact.

David House, of the Bradley Manning Support Network, stated publicly, and repeatedly, that U.S. investigative authorities attempted to bribe him to become an informant and infiltrate WikiLeaks activities.

I have been told that the girlfriend of a Berlin-based Israeli intelligence officer attended the wedding of ADB and DDB. This may not be significant.

I have received intelligence from current Western intelligence officer, that Anke Domscheit Berg, personally, came into contact with the CIA during her time working for the McKinsey & Company consulting group. This was a direct, volunteered statement of fact and warning, and not a statement of speculation. I do not know if ADB was complicit in the reported
contact.

J Assange 

*

WikiLeaks editorial 1 September 2011: Guardian journalist negligently disclosed Cablegate passwords

https://wikileaks.org/Guardian-journalist-negligently.html

A Guardian journalist has negligently disclosed top secret WikiLeaks' decryption passwords to hundreds of thousands of unredacted unpublished US diplomatic cables.

Knowledge of the Guardian disclosure has spread privately over several months but reached critical mass last week. The unpublished WikiLeaks' material includes over 100,000 classified unredacted cables that were being analyzed, in parts, by over 50 media and human rights organizations from around the world.

For the past month WikiLeaks has been in the unenviable position of not being able to comment on what has happened, since to do so would be to draw attention to the decryption passwords in the Guardian book. Now that the connection has been made public by others we can explain what happened and what we intend to do.

WikiLeaks has commenced pre-litigation action against the Guardian and an individual in Germany who was distributing the Guardian passwords for personal gain.

Over the past nine months, WikiLeaks has been releasing US diplomatic cables according to a carefully laid out plan to stimulate profound changes. A number of human rights groups, including Amnesty International, believe that the co-ordinated release of the cables contributed to triggering the Arab Spring. By forming partnerships with over 90 other media and human rights organizations WikiLeaks has been laying the ground for positive political change all over the world.

The WikiLeaks method involves a sophisticated procedure of packaging leaked US diplomatic cables up into country groups or themes, such as 'resources corruption', and providing it to those organizations that agreed to do the most research in exchange for time-limited exclusivity. As part of the WikiLeaks agreement, these groups, using their local knowledge, remove the names of persons reporting unjust acts to US embassies, and feed the results back to WikiLeaks. WikiLeaks then publishes, simultaneously with its partners, the underlying cables together with the politically explosive revelations. This way publications that are too frightened to publish the cables have the proof they need, and the public can check to make sure the claims are accurate.

Over time WikiLeaks has been building up, and publishing, the complete Cablegate "library"--the most significant political document ever published. The mammoth task of reading and lightly redacting what amounts to 3,000 volumes or 284 million words of global political history is shared by WikiLeaks and its partners. That careful work has been compromised as a result of the recklessness of the Guardian.

Revolutions and reforms are in danger of being lost as the unpublished cables spread to intelligence contractors and governments before the public. The Arab Spring would not have started in the manner it did if the Tunisian government of Ben Ali had copies of those WikiLeaks releases which helped to take down his government. Similarly, it is possible that the torturing Egyptian internal security chief, Suleiman--Washington's proposed replacement for Mubarak--would now be the acting ruler of Egypt, had he acquired copies of the cables that exposed his methods prior to their publication.

Indeed, it is one of the indelible stains on Hillary Clinton that she personally set course to forewarn dozens of corrupt leaders, including Hosni Mubarak, about some of the most powerful details of WikiLeaks' revelations to come.

Every day that the corrupt leadership of a country or organization knows of a pending WikiLeaks disclosure is a day spent planning how to crush revolution and reform.

Guardian investigations editor, David Leigh, recklessly, and without gaining our approval, knowingly disclosed the decryption passwords in a book published by the Guardian. Leigh states the book was rushed forward to be written in three weeks--the rights were then sold to Hollywood.

The following extract is from the Guardian book:

{Leigh tried his best not to fall out with this Australian impresario, who was prone to criticise what he called the “snaky Brits”. Instead, Leigh used his ever-shifting demands as a negotiating lever. “You want us to postpone the Iraq logs’ publication so you can get some TV,” he said. [WikiLeaks: We required more time for redactions and to complete three Iraq war documentaries commissioned through the Bureau of Investigative Journalism. The documentaries were syndicated through Channel 4 (UK) and al Jazeera English and Arabic] “We could refuse, and simply go ahead with publication as planned. If you want us to do something for you, then you’ve got to do something for us as well.” He asked Assange to stop procrastinating, and hand over the biggest trove of all: the cables. Assange said, “I could give you half of them, covering the first 50% of the period.”

Leigh refused. All or nothing, he said. “What happens if you end up in an orange jump-suit en route to Guantánamo before you can release the full files?” In return he would give Assange a promise to keep the cables secure, and not to publish them until the time came. Assange had always been vague about timing: he generally indicated, however, that October would be a suitable date. He believed the US army’s charges against the imprisoned soldier Bradley Manning would have crystallised by then, and publication could not make his fate any worse. He also said, echoing Leigh’s gallows humour: “I’m going to need to be safe in Cuba first!” Eventually, Assange capitulated. Late at night, after a two-hour debate, he started the process on one of his little netbooks that would enable Leigh to download the entire tranche of cables. The Guardian journalist had to set up the PGP encryption system on his laptop at home across the other side of London. Then he could feed in a password. Assange wrote down on a scrap of paper:

[WikiLeaks: we have replaced the password with Xs] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

“That’s the password,” he said. “But you have to add one extra word when you type it in. You have to put in the word ‘XXXXXXX’ before the word ‘XXXXXX’ [WikiLeaks: so if the paper were seized, the password would not work without Leigh's co-operation] Can you remember that?” “I can remember that.” Leigh set off home, and successfully installed the PGP software.}

The Guardian disclosure is a violation of the confidentiality agreement between WikiLeaks and Alan Rusbridger, editor-in-chief of the Guardian, signed July 30, 2010. David Leigh is also Alan Rusbridger's brother in law, which has caused other Guardian journalists to claim that David Leigh has been unfairly protected from the fallout. It is not the first time the WikiLeaks security agreement has been violated by the Guardian.

WikiLeaks severed future projects with the Guardian in December last year after it was discovered that the Guardian was engaged in a conspiracy to publish the cables without the knowledge of WikiLeaks, seriously compromising the security of our people in the United States and an alleged source who was in pre-trial detention. Leigh, without any basis, and in a flagrant violation of journalistic ethics, named Bradley Manning as the Cablegate source in his book. David Leigh secretly passed the entire archive to Bill Keller of the New York Times, in September 2011, or before, knowingly destroying WikiLeaks plans to publish instead with the Washington Post & McClatchy.

David Leigh and the Guardian have subsequently and repeatedly violated WikiLeaks security conditions, including our requirements that the unpublished cables be kept safe from state intelligence services by keeping them only on computers not connected to the internet. Ian Katz, Deputy Editor of the Guardian admitted in December 2010 meeting that this condition was not being followed by the Guardian.

PJ Crowley, State Department spokesman on the cables issue earlier this year, told AP on the 30th of August, 2011 that “any autocratic security service worth its salt” would probably already have the complete unredacted archive.

Two weeks ago, when it was discovered that information about the Leigh book had spread so much that it was about to be published in the German weekly Freitag, WikiLeaks took emergency action, asking the editor not allude to the Leigh book, and tasked its lawyers to demand those maliciously spreading its details about the Leigh book stop.

WikiLeaks advanced its regular publication schedule, to get as much of the material as possible into the hands of journalists and human rights lawyers who need it. WikiLeaks and its partners were scheduled to have published most of the Cablegate material by November 29, 2011 – one year since the first publication. Over the past week, we have published over 130,000 cables, mostly unclassified. The cables have lead to hundreds of important news stories around the world. All were unclassified with the exception of the Australian, Swedish collections, and a few others, which were scheduled by our partners.

WikiLeaks has also been in contact with Human Rights Watch and Amnesty at a senior level. We contacted the US embassy in London and then the State Department in Washington on 25 August to see if their informant notification program, instituted last year, was complete, and if not, to take such steps as would be helpful. Only after repeated attempts through high level channels and 36 hours after our first contact, did the State Department, although it had been made aware of the issue, respond. Cliff Johnson (a legal advisor at the Department of State) spoke to Julian Assange for 75 minutes, but the State Department decided not to meet in person to receive further information, which could not, at that stage, be safely transmitted over the telephone.

* 

Renata Avila open letter August 2011: https://web.archive.org/web/20160201071005/http://nothingispermanent.blogspot.com.au/2011/08/open-letter.html

* 

20 August 2011 DDB destroys archive: https://shadowproof.com/2011/08/21/openleaks-founder-destroys-cache-of-unreleased-wikileaks-documents/
by Kevin Gosztola

*

NYT Scott Shane link:https://www.nytimes.com/2011/08/30/us/30wikileaks.html?_r=1&ref=world&gwh=88BDFA564D6DAF5A757D1B85518B48D2[wrote] on 29 August 2001

> The disclosures take place as a federal grand jury in Alexandria, Va., continues to hear evidence in a criminal investigation of WikiLeaks for disclosing classified information.

WikiLeaks Leaves Names of Diplomatic Sources in Cables

By Scott Shane

    Aug. 29, 2011

WASHINGTON — In a shift of tactics that has alarmed American officials, the antisecrecy organization WikiLeaks has published on the Web nearly 134,000 leaked diplomatic cables in recent days, more than six times the total disclosed publicly since the posting of the leaked State Department documents began last November.

A sampling of the documents showed that the newly published cables included the names of some people who had spoken confidentially to American diplomats and whose identities were marked in the cables with the warning “strictly protect.”

State Department officials and human rights activists have been concerned that such diplomatic sources, including activists, journalists and academics in authoritarian countries, could face reprisals, including dismissal from their jobs, prosecution or violence.

Since late 2010, The New York Times and several other news organizations have had access to more than 250,000 State Department cables originally obtained by WikiLeaks, citing them in news articles and publishing a relatively small number of cables deemed newsworthy. But The Times and other publications that had access to the documents removed the names of people judged vulnerable to retaliation.

WikiLeaks published some cables on its own Web site, but until the latest release, the group had also provided versions of the cables that had been edited to protect low-level diplomatic sources.

Government officials and journalists were poring over the newly released cables on Monday to assess whether people named in them might face repercussions. A quick sampling found at least one cable posted on Monday, from the American Embassy in Australia, had a name removed, but several others left in the identities of people whom diplomats had flagged for protection.

    Unlock more free articles.

Create an account or log in

Among those named, despite diplomats’ warnings, were a United Nations official in West Africa and a foreign human rights activist working in Cambodia. They had spoken candidly to American Embassy officials on the understanding that they would not be publicly identified.

The new disclosures are likely to reignite a debate over the virtues and perils of making public the confidential views of American diplomats, some of whom have complained that the leaks have made their work more difficult. The disclosures take place as a federal grand jury in Alexandria, Va., continues to hear evidence in a criminal investigation of WikiLeaks for disclosing classified information.
ImageThe WikiLeaks founder, Julian Assange, arriving at High Court in London in July.
The WikiLeaks founder, Julian Assange, arriving at High Court in London in July.Credit...Sang Tan/Associated Press

WikiLeaks said in a statement on Monday that the acceleration in disclosing the cables was “in accordance with WikiLeaks’s commitment to maximizing impact and making information available to all.” The statement suggested that it was intended to counter the “misperception” that the organization “has been less active in recent months.”
Editors’ Picks
The Neighborhood Name Game
‘The Plot Against America’ Imagines the Rise of an Intolerant Demagogue
The Bard of American Privilege

The statement said that “crowdsourcing” the documents by posting them will allow people of different backgrounds and nationalities to interpret the cables. It was unsigned, but WikiLeaks’s founder, Julian Assange, generally drafts or approves the group’s statements.

Even as WikiLeaks made its new postings, a German publication reported that an encrypted file containing all of the 251,287 diplomatic cables obtained by WikiLeaks last year had been posted months ago on the Web, and that the password was also available on the Internet. It was unclear on Monday whether anyone had cracked the encrypted file described by the publication, Der Freitag, a small Berlin-based, left-leaning weekly, and had made public previously unpublished material.

A State Department spokesman, Michael A. Hammer, said the department would not comment on the authenticity of the documents released. He said the United States “strongly condemns any illegal disclosure of classified information.”

Last year, WikiLeaks was sharply criticized by human rights activists for disclosing the names of Afghan citizens who had provided information on the Taliban to the American military. It was far more cautious in subsequent releases, using software to strip proper names out of Iraq war documents and publishing versions of the cables after they had been edited by The New York Times and other publications.

The publication of cables began slowly last year, with only 2,500 made public by year’s end, often with redactions. As of last week, the total had reached about 20,000.

But the State Department has always acted on the assumption that all quarter-million cables might become public. A department task force worked with American embassies to review all the leaked cables, quietly warning people named in the cables that they might be in jeopardy. Some especially vulnerable people were given help to move, usually outside their home countries.

Steven Aftergood, an expert on government secrecy at the Federation of American Scientists, said he had reviewed several dozen cables from the new batch — all among those classified “secret” by the State Department — and found only one redaction. He said the volume of the new release made it unlikely that all the information that might endanger diplomatic sources had been removed.

“If these cables have not been carefully reviewed, it’s likely to be problematic for any number of people named in the cables,” Mr. Aftergood said.

Der Spiegel link:https://www.spiegel.de/international/world/leak-at-wikileaks-a-dispatch-disaster-in-six-acts-a-783778.html[blamed] "a series of mistakes made by several different people."

> A Dispatch Disaster in Six Acts
Some 250,000 diplomatic dispatches from the US State Department have accidentally been made completely public. The files include the names of informants who now must fear for their lives. It is the result of a series of blunders by WikiLeaks and its supporters.
Von Christian Stöcker
01.09.2011, 13:00 Uhr

In the end, all the efforts at confidentiality came to naught. Everyone who knows a bit about computers can now have a look into the 250,000 US diplomatic dispatches that WikiLeaks made available to select news outlets late last year. All of them. What's more, they are the unedited, unredacted versions complete with the names of US diplomats' informants -- sensitive names from Iran, China, Afghanistan, the Arab world and elsewhere.

SPIEGEL reported on the secrecy slip-up last weekend, but declined to go into detail. Now, however, the story has blown up. And is one that comes as a result of a series of mistakes made by several different people. Together, they add up to a catastrophe. And the series of events reads like the script for a B movie.

Act One: The Whistleblower and the Journalist

The story began with a secret deal. When David Leigh of the Guardian finally found himself sitting across from WikiLeaks founder Julian Assange, as the British journalist recounts in his book "Inside Julian Assange's War on Secrecy", the two agreed that Assange would provide Leigh with a file including all of the diplomatic dispatches received by WikiLeaks.

Assange placed the file on a server and wrote down the password on a slip of paper -- but not the entire password. To make it work, one had to complete the list of characters with a certain word. Can you remember it? Assange asked. Of course, responded Leigh.

It was the first step in a disclosure that became a worldwide sensation. As a result of Leigh's meeting with Assange, not only the Guardian, but also the New York Times, SPIEGEL and other media outlets published carefully chosen -- and redacted -- dispatches. Editors were at pains to black out the names of informants who could be endangered by the publication of the documents.

Act Two: The German Spokesman Takes the Dispatch File when Leaving WikiLeaks

At the time, Daniel Domscheit-Berg, who later founded the site OpenLeaks, was the German spokesman for WikiLeaks. When he and others undertook repairs on the WikiLeaks server, he took a dataset off the server which contained all manner of files and information that had been provided to WikiLeaks. What he apparently didn't know at the time, however, was that the dataset included the complete collection of diplomatic dispatches hidden in a difficult-to-find sub-folder.

After making the data in this hidden sub-folder available to Leigh, Assange apparently simply left it there. After all, it seemed unlikely that anyone would ever find it.

But now, the dataset was in the hands of Domscheit-Berg. And the password was easy to find if one knew where to look. In his book Leigh didn't just describe his meeting with Assange, but he also printed the password Assange wrote down on the slip of paper complete with the portion he had to remember.

Act Three: Well-Meaning Helpers Accidentally Put the Cables into Circulation

Immediately after the first diplomatic dispatches were made public, WikiLeaks became the target of several denial-of-service attacks and several US companies, including Mastercard, PayPal and Amazon, withdrew their support. Quickly, several mirror servers were set up to prevent WikiLeaks from disappearing completely from the Internet. Well-meaning WikiLeaks supporters also put online a compressed version of all data that had been published by WikiLeaks until that time via the filesharing protocol BitTorrent.

BitTorrent is decentralized. Data which ends up on several other computers via the site can essentially no longer be recalled. As a result, WikiLeaks supporters had in their possession the entire dataset that Domscheit-Berg took off the WikiLeaks server, including the hidden data file. Presumably thousands of WikiLeaks sympathizers -- and, one supposes, numerous secret service agents -- now had copies of all previous WikiLeaks publications on their hard drives.

And, what they didn't know, a password-protected copy of all the diplomatic dispatches from the US State Department.

Act Four: Mudslinging between Assange and Domscheit-Berg

To make matters worse, Julian Assange and Daniel Domscheit-Berg then had a falling out. The German spokesman wrote a vengeful book after being thrown out of WikiLeaks in which he portrayed the WikiLeaks founder as an unreliable egomaniac who tended toward latent megalomania.

Predictably, Assange was furious and made several statements that were intended to besmirch Domscheit-Berg. But when he repaired the WikiLeaks server, Domscheit-Berg apparently didn't just take all of the collected WikiLeaks documents, but he also took the secure submission system designed to allow whistleblowers to anonymously submit data. As a result, WikiLeaks was temporarily out of action.

Domscheit-Berg also repeatedly accused Assange of not being sufficiently vigilant about protecting his sources. And he launched a competing platform called OpenLeaks which he is now developing with other former WikiLeaks employees and other supporters.

Act Five : Exposed Disclosures

The conflict between Domscheit-Berg and Assange has become increasingly aggressive. Germany's Chaos Computer Club recently made the surprising decision to revoke Domscheit-Berg's membership because he allegedly misused their name to hype his OpenLeaks project. While that was their official reason, unofficially the tension stems from the data that Domscheit-Berg took with him from Wikileaks.

In an effort to prove that Assange couldn't be trusted, people associated with the OpenLeaks project recently began talking about the hidden diplomatic cables -- and the dataset which has been coursing through the Internet for months, though no one knew about it.

Then someone betrayed the location of the password -- Leigh's book -- to a journalist for German weekly Der Freitag, which is also an OpenLeaks partner. The weekly published a cautiously formulated version of the story, that without naming the exact location of the password, still revealed it was "out in the open and identifiable to those familiar with the material." Speculation on Twitter and elsewhere ran wild, and hobby investigators began to edge closer to which password it could be.

Meanwhile the mudslinging continued unabated between Assange and Domscheit-Berg.

Act Six: Cablegate-Gate

An account of the story of Leigh, the hidden data and the password then cropped up on a platform normally used by open-source developers to exchange programming codes. A link to the entry spread quickly through Twitter. Suddenly, anyone could access the entire "Cablegate" file with a bit of effort.

On Wednesday afternoon the Wikileaks Twitter account announced "important news," and a few hours later character sequences and links were distributed to download an encoded, 550-megabyte file via a BitTorrent client. The password was to be delivered later.

The distribution apparently didn't work at first, and complaints appeared on Twitter. But later the problem was fixed, and the data began to circulate.

It remains unclear whether this was the Cablegate data set. Meanwhile Wikileaks' Twitter account has called on users to vote on whether they agree with the publication of the unredacted cables. They can register their vote with the hashtag "WLVoteYes" or "WLVoteNo" on Twitter.

A Wikileaks statement on Twitter blames the Guardian and Leigh for the fact that the cables are now freely available online. "We have already spoken to the (US) State Department and commenced pre-litigation action," it said, adding that their targets were the Guardian and a person in Germany who gave out the paper's password. Leigh breached a confidentiality agreement between Wikileaks and the Guardian, it added. The US Embassy in London and the US State Department had been notified of the possible publication already on August 25 so that officials could warn informants.

In a statement the Guardian rejected the accusations from Wikileaks, explaining that the paper had been told the password was temporary and would be deleted within hours. "No concerns were expressed when the book was published and if anyone at WikiLeaks had thought this compromised security they have had seven months to remove the files," the statement said. "That they didn't do so clearly shows the problem was not caused by the Guardian's book."

Finale: In the Open

It is possible that intelligence agencies in a number of countries have already gained access to the data. "Any autocratic security service worth its salt" would have already done so, former US Assistant Secretary of State for Public Affairs P.J. Crowley told news agency AP on Wednesday. Intelligence agencies that haven't already gotten their hands on the data "will have it in short order," he added.

By Wednesday evening Crowley's prediction was confirmed. The "Cablegate" cables are now completely public. For many people in totalitarian states this could prove life-threatening. For Wikileaks, OpenLeaks, Julian Assange, Daniel Domscheit-Berg and many others, it is nothing short of a catastrophe.

A chain of careless mistakes, coincidences, indiscretions and confusion now means that no potential whistleblower would feel comfortable turning to a leaking platform right now. They appear to be out of control.


A link:https://wikileaks.org/Guardian-journalist-negligently.html[statement] was released by WikiLeaks on 1 September 2011:

> Guardian journalist negligently disclosed Cablegate passwords
1 September 2011
01 September 2011

WIKILEAKS EDITORIAL

A Guardian journalist has negligently disclosed top secret WikiLeaks' decryption passwords to hundreds of thousands of unredacted unpublished US diplomatic cables.

Knowledge of the Guardian disclosure has spread privately over several months but reached critical mass last week. The unpublished WikiLeaks' material includes over 100,000 classified unredacted cables that were being analyzed, in parts, by over 50 media and human rights organizations from around the world.

For the past month WikiLeaks has been in the unenviable position of not being able to comment on what has happened, since to do so would be to draw attention to the decryption passwords in the Guardian book. Now that the connection has been made public by others we can explain what happened and what we intend to do.

WikiLeaks has commenced pre-litigation action against the Guardian and an individual in Germany who was distributing the Guardian passwords for personal gain.

Over the past nine months, WikiLeaks has been releasing US diplomatic cables according to a carefully laid out plan to stimulate profound changes. A number of human rights groups, including Amnesty International, believe that the co-ordinated release of the cables contributed to triggering the Arab Spring. By forming partnerships with over 90 other media and human rights organizations WikiLeaks has been laying the ground for positive political change all over the world.

The WikiLeaks method involves a sophisticated procedure of packaging leaked US diplomatic cables up into country groups or themes, such as 'resources corruption', and providing it to those organizations that agreed to do the most research in exchange for time-limited exclusivity. As part of the WikiLeaks agreement, these groups, using their local knowledge, remove the names of persons reporting unjust acts to US embassies, and feed the results back to WikiLeaks. WikiLeaks then publishes, simultaneously with its partners, the underlying cables together with the politically explosive revelations. This way publications that are too frightened to publish the cables have the proof they need, and the public can check to make sure the claims are accurate.

Over time WikiLeaks has been building up, and publishing, the complete Cablegate "library"--the most significant political document ever published. The mammoth task of reading and lightly redacting what amounts to 3,000 volumes or 284 million words of global political history is shared by WikiLeaks and its partners. That careful work has been compromised as a result of the recklessness of the Guardian.

Revolutions and reforms are in danger of being lost as the unpublished cables spread to intelligence contractors and governments before the public. The Arab Spring would not have started in the manner it did if the Tunisian government of Ben Ali had copies of those WikiLeaks releases which helped to take down his government. Similarly, it is possible that the torturing Egyptian internal security chief, Suleiman--Washington's proposed replacement for Mubarak--would now be the acting ruler of Egypt, had he acquired copies of the cables that exposed his methods prior to their publication.

Indeed, it is one of the indelible stains on Hillary Clinton that she personally set course to forewarn dozens of corrupt leaders, including Hosni Mubarak, about some of the most powerful details of WikiLeaks' revelations to come.

Every day that the corrupt leadership of a country or organization knows of a pending WikiLeaks disclosure is a day spent planning how to crush revolution and reform.

Guardian investigations editor, David Leigh, recklessly, and without gaining our approval, knowingly disclosed the decryption passwords in a book published by the Guardian. Leigh states the book was rushed forward to be written in three weeks--the rights were then sold to Hollywood.

The following extract is from the Guardian book:

{Leigh tried his best not to fall out with this Australian impresario, who was prone to criticise what he called the “snaky Brits”. Instead, Leigh used his ever-shifting demands as a negotiating lever. “You want us to postpone the Iraq logs’ publication so you can get some TV,” he said. [WikiLeaks: We required more time for redactions and to complete three Iraq war documentaries commissioned through the Bureau of Investigative Journalism. The documentaries were syndicated through Channel 4 (UK) and al Jazeera English and Arabic] “We could refuse, and simply go ahead with publication as planned. If you want us to do something for you, then you’ve got to do something for us as well.” He asked Assange to stop procrastinating, and hand over the biggest trove of all: the cables. Assange said, “I could give you half of them, covering the first 50% of the period.”

Leigh refused. All or nothing, he said. “What happens if you end up in an orange jump-suit en route to Guantánamo before you can release the full files?” In return he would give Assange a promise to keep the cables secure, and not to publish them until the time came. Assange had always been vague about timing: he generally indicated, however, that October would be a suitable date. He believed the US army’s charges against the imprisoned soldier Bradley Manning would have crystallised by then, and publication could not make his fate any worse. He also said, echoing Leigh’s gallows humour: “I’m going to need to be safe in Cuba first!” Eventually, Assange capitulated. Late at night, after a two-hour debate, he started the process on one of his little netbooks that would enable Leigh to download the entire tranche of cables. The Guardian journalist had to set up the PGP encryption system on his laptop at home across the other side of London. Then he could feed in a password. Assange wrote down on a scrap of paper:

[WikiLeaks: we have replaced the password with Xs] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

“That’s the password,” he said. “But you have to add one extra word when you type it in. You have to put in the word ‘XXXXXXX’ before the word ‘XXXXXX’ [WikiLeaks: so if the paper were seized, the password would not work without Leigh's co-operation] Can you remember that?” “I can remember that.” Leigh set off home, and successfully installed the PGP software.}

The Guardian disclosure is a violation of the confidentiality agreement between WikiLeaks and Alan Rusbridger, editor-in-chief of the Guardian, signed July 30, 2010. David Leigh is also Alan Rusbridger's brother in law, which has caused other Guardian journalists to claim that David Leigh has been unfairly protected from the fallout. It is not the first time the WikiLeaks security agreement has been violated by the Guardian.

WikiLeaks severed future projects with the Guardian in December last year after it was discovered that the Guardian was engaged in a conspiracy to publish the cables without the knowledge of WikiLeaks, seriously compromising the security of our people in the United States and an alleged source who was in pre-trial detention. Leigh, without any basis, and in a flagrant violation of journalistic ethics, named Bradley Manning as the Cablegate source in his book. David Leigh secretly passed the entire archive to Bill Keller of the New York Times, in September 2011, or before, knowingly destroying WikiLeaks plans to publish instead with the Washington Post & McClatchy.

David Leigh and the Guardian have subsequently and repeatedly violated WikiLeaks security conditions, including our requirements that the unpublished cables be kept safe from state intelligence services by keeping them only on computers not connected to the internet. Ian Katz, Deputy Editor of the Guardian admitted in December 2010 meeting that this condition was not being followed by the Guardian.

PJ Crowley, State Department spokesman on the cables issue earlier this year, told AP on the 30th of August, 2011 that “any autocratic security service worth its salt” would probably already have the complete unredacted archive.

Two weeks ago, when it was discovered that information about the Leigh book had spread so much that it was about to be published in the German weekly Freitag, WikiLeaks took emergency action, asking the editor not allude to the Leigh book, and tasked its lawyers to demand those maliciously spreading its details about the Leigh book stop.

WikiLeaks advanced its regular publication schedule, to get as much of the material as possible into the hands of journalists and human rights lawyers who need it. WikiLeaks and its partners were scheduled to have published most of the Cablegate material by November 29, 2011 – one year since the first publication. Over the past week, we have published over 130,000 cables, mostly unclassified. The cables have lead to hundreds of important news stories around the world. All were unclassified with the exception of the Australian, Swedish collections, and a few others, which were scheduled by our partners.

WikiLeaks has also been in contact with Human Rights Watch and Amnesty at a senior level. We contacted the US embassy in London and then the State Department in Washington on 25 August to see if their informant notification program, instituted last year, was complete, and if not, to take such steps as would be helpful. Only after repeated attempts through high level channels and 36 hours after our first contact, did the State Department, although it had been made aware of the issue, respond. Cliff Johnson (a legal advisor at the Department of State) spoke to Julian Assange for 75 minutes, but the State Department decided not to meet in person to receive further information, which could not, at that stage, be safely transmitted over the telephone.

Wikileaks link:https://twitter.com/wikileaks/status/109386723066257409[tweeted] on 2 September 2011: 

> It is strictly false that the Guardian was told the password or file were temporary, hence the elaborate password handover method. 

Random website 1 September 2011 https://mybroadband.co.za/news/internet/33086-wikileaks-how-the-leak-was-leaked.html 

> According to an account by Guardian journalist David Leigh, Assange gave the unredacted cables to The Guardian in the summer of 2010 by temporarily placing an encrypted file on an obscure website. Leigh was given a password which unlocked this file.

A few months later, Wikileaks publicly posted a huge archive of previously released material to ensure continued access to it following Assange’s legal troubles and attacks on their website.

At that time only a few thousand of the more than 250,000 cables had been published, and only in redacted form to protect US diplomatic sources.

Although the 250,000 cables were not in the archive, it included a mysterious encrypted file called “z.gpg” – which appears to have been created months before Wikileaks gave the cables to the media.

In February 2011, Leigh’s book “WikiLeaks: Inside Julian Assange’s War on Secrecy” was published. In it he described how Assange passed the cables to the Guardian, along with the password he was given.

There matters sat until Aug. 25 when the website of German newspaper Der Freitag connected the old password with the mysterious “z.gpg” file, although they did not name the file or print the password.

But others clearly knew. By Wednesday, Aug. 29th, a few Twitter users were hinting that the password in Leigh’s book worked, and others were drawing attention to “z.gpg.” Within hours, public links to the full, unencrypted cables appeared.

By Thursday morning, the cables were easily available from several file sharing sites commonly used for pirated music and movies.


Nigel Parry's version of events was published 31 August 2011 but is now deleted. I can still be read link:https://web.archive.org/web/20111011051414/http://nigelparry.com/news/guardian-david-leigh-cablegate.shtml[here]: 

> I remember reading this shortly after the book was released and instinctively thinking "bad idea".

On a basic security level, revealing any information about how Julian Assange formulates his passwords could have implications in any of the other myriad of sensitive areas Wikileaks deals with. Any files encrypted by Assange at the same time—or before—the cables, and in the possession of any entity hostile to Wikileaks, are now more vulnerable since Leigh's book gave up its clue about how Assange formulates passwords.

And anyone who has access to the original file David Leigh was given, could now decrypt it. Unless the original file was carefully protected throughout its entire life, decrypted and unzipped, then destroyed after the data was released, that password will work on copies of it for ever. No backsies. So regardless how David Leigh & Co. imagine computer security works—and right now they are desperately trying increasingly ridiculous arguments to blame Wikileaks for Leigh's actions—there's no reason to publish any password this sensitive—ever.

The entire Leigh/Harding Wikileaks book is written in the thrilled tone of a girl scout's diary, clearly reveling in the secret squirrel aspect of the story. And they're clearly clueless too. Leigh at one point drives across town so Assange can show him how to unzip the Cablegate file. Perhaps not the best people to share secrets with.

Cat out the bag
On August 25th, Der Freitag reported that a file containing the unredacted cables was available on the Internet. TechCrunch summarized the story a couple of days later:

    In the story, published on Friday, editor Steffen Kraft claims to have found online a “password protected csv file” containing a 1.73GB cache of entirely unredacted diplomatic cables, originating from Wikileaks. According to Kraft, the password for the file is also easy to locate.


On August 29th, Der Spiegel confirmed the story...MORE IF WANTED

From the two German reports, it became clear that a torrented mirror of Wikileaks had accidently included an encrypted copy of the Cablegate cables. And that the password was easy to find on the Internet.

This last part immediately brought to mind the Guardian's Wikileaks book and David Leigh and Luke Harding's inexplicable need to tell people the password for the original encrypted Cablegate file.

Meanwhile, none of the German reporters wanted to be the one to mention which password and which archive. In the case of both, there aren't that many options.

It was Domscheit-Berg who allegedly connected the dots for the German media organizations. Unparalleled Wikileaks news follower and gatherer Asher Wolf later perhaps best summed up the tangled web with a tweet quoting an anonymous Twitter user, @Nin_99, who played a significant role in the treasure hunt:

    wl fucked up b/c they had file on public server, leigh fucked up b/c he told everyone the pw, ddb told everyone who would listen about all


Surely it couldn't be that easy? In the evening of August 30th, I started searching the various Wikileaks torrents online and that I'd downloaded, looking in directories for encrypted file. I wrote to several of the German journalists who had broke the story and asked them outright if David Leigh's password opened the archive. No response. I asked David Leigh himself. He declined to respond.

I tweeted other people who closely follow the Wikileaks story. It was a treasure hunt with clues. Anonymous Twitter user, @Nin_99, joined in and messaged us, pointing to a suspicious directory on a downloaded Wikileaks torrent, shared online:


    @flyingmonkeyair @JLLLOW @Asher_Wolf @m_cetera Anyone might guess what's in these here: http://193.198.207.6/wiki/file/xyz/ (from torrent)

    https://twitter.com/#!/Nin_99/status/108988882862870529


@Nin_99 had been exploring the directory for a few days, trying different passwords on it.

In the directory, date-stamped 9 June 2010, were 4 files, all encoded with Pretty Good Privacy (PGP) encoding, the files names with *.gpg suffixes.

I started at the bottom of the list, putting in the David Leigh password. It unzipped z.gpg into a file called z.7z. Opening that file and extracting it using the Ez7z compression/decompression program, the file spat out a file called cables.csv, dated with a creation date of April 12, 2010 at 9:22PM.

It was a 1.61GB file but it had been reported in the German press to be 1.73GB. A closer look at my file system reporting showed the file size to be both 1.61 GB and 1,730,507,223 bytes. It was easy to see how the byte amount could be mistranslated as 1.73GB.

So there it was. After Wikileaks, the various media partners, Aftenposten—who apparently scored a copy of cables.csv back in December 2010—and the German reporters, I was the first person out of the loop and in the wild to have unzipped the unredacted Cablegate cables.

I private messaged @Nin_99 to save them some time and let them know the password opened z.gpg.

Game over at this point. The cat was forever out of the bag. Regardless even of what we both did, it was only a matter of time before someone else unpacked the unredacted cables. The various media organization's hints were more than enough.

I tweeted:


    It's a bad day for @DavidLeigh3 & the Guardian. His book password decrypts an old wikileaks.org dir file into cables.csv, 1.61GB #Cablegate

    https://twitter.com/#!/flyingmonkeyair/status/109022484065562624


and a minute or so later:

    Just to be clear: I ran the password from p139 of @DavidLeigh3's book and it opened into cables.csv #Wikileaks #FAIL

    https://twitter.com/#!/flyingmonkeyair/status/109022790035836928


It was a tense minute or so after I first unzipped the cables. The bigger the secrets, the bigger the sense of personal responsibility. If the United States government was unhappy about redacted cables being released by media organizations, it was going to have a giant WikiCow about the unredacted ones being released to the whole world.

I e-mailed Wikileaks, copying the tweet URL. Whether in response or not, Wikileaks sprung into action and released a statement within 20 minutes:

    Statement on the betrayal of WikiLeaks passwords by the Guardian.

    GMT Wed Aug 31 22:27:48 2011 GMT

    A Guardian journalist has, in a previously undetected act of gross negligence or malice, and in violation a signed security agreement with the Guardian's editor-in-chief Alan Rusbridger, disclosed top secret decryption passwords to the entire, unredacted, WikiLeaks Cablegate archive. We have already spoken to the State Department and commenced pre-litigation action. We will issue a formal statement in due course.

    WIKILEAKS


Within an hour, @Nin_99 had uploaded the unredacted cables onto the Internet, and within a couple of hours, the cables were also available at longtime transparency website Cryptome.org.


Guardian article by Leigh and Ball 1 September 2011: link:https://web.archive.org/web/20110902072536/http://www.guardian.co.uk/media/2011/sep/01/wikileaks-make-public-all-state-cables[WikiLeaks decides to make public all US state department cables] 

> WikiLeaks decides to make public all US state department cables

Information related to confidential informants will not be redacted, despite fears for their safety

    David Leigh and James Ball
    guardian.co.uk, Thursday 1 September 2011 21.28 BST	
    Article history

Julian Assnage To Appeal Against Extradition
WikiLeaks founder Julian Assange at the High Court in London in July. Photograph: Andy Rain/EPA

WikiLeaks and its founder, Julian Assange, parted company with mainstream opinion when Assange revealed his intention to make public all 250,000 raw US state department cables that have been in his hands since last year, regardless of possible reprisals to named individuals. This flies in the face of efforts by the Guardian and other news organisations to redact references to confidential informants before publishing selected cables: efforts which may now appear to have been largely wasted.

Assange's plans were foreshadowed at a secret meeting of the WikiLeaks team last November. The diary of one of those present at Ellingham Hall, the stately home which was then their base, records: "Heated conversation about rough plans on releasing cables … JA insistent all cables must somehow eventually be released." His wish has now been realised, after a year punctuated by his arrest, heated quarrels with former associates, and a chapter of accidents within Assange's chaotic organisation. A few days after the Ellingham Hall meeting Assange turned himself in for arrest on an extradition warrant sought by Sweden, on allegations of sexual assault by two young WikiLeaks supporters there. He is still fighting extradition.

On 7 December, the day of his arrest, a huge file of WikiLeaks information was posted on the Pirate Bay filesharing site by one of his supporters. According to the group's former No 2, computer expert Daniel Domscheit-Berg: "These people said they wanted to keep WikiLeaks operational, but they never spoke to Julian." As a result, it was never apparently realised that the file-set included Assange's copy of all the classified US cables.

Earlier in the year, according to Domscheit-Berg, Assange gave a copy of the cables file to the Guardian, one of the news organisations with whom he had agreed to work to publish the cables in redacted form. He provided the Guardian with a password and access to a special online server, on which he said he would place a copy of the cables file, which would only remain in existence for a short time. What Assange did not reveal was that he had not followed conventional security practice and created a new password for the transaction. Instead, according to Domscheit-Berg, he had merely reused the existing master password, already known to others within WikiLeaks. "The file was never supposed to be shared with anyone at all. To get a copy you would usually make a new copy with a new password. He was too lazy to create something new."

Early this year the Guardian published a book on WikiLeaks. In the course of it the password Assange had provided, assumed to be long obsolete, was published. The book contained no information that would enable anyone to find and download the encrypted file.

This series of events has had unplanned consequences in recent weeks. Domscheit-Berg, who says he parted company with Assange over security concerns among other reasons, ended up alleging to a German newspaper, Freitag, that WikiLeaks was insecure. He said a file existed on the internet that contained the raw cables, and was capable of being accessed by the published password. He and Freitag took care to provide no location information that would enable the file to be accessed by any member of the public.

The quarrel with Domscheit-Berg seemed to have had seismic consequences for Assange, who is still awaiting the result of his extradition appeal. He published unsubstantiated accusations that Domscheit-Berg had links with western intelligence agencies, and started to pump out tens of thousands of previously unpublished cables, mostly apparently unredacted. "He feared he would not be the one any more to be publishing them," says Domscheit-Berg. "He is so egocentric and completely irrational."

To protests from the Australian and US governments that he was endangering sources, Assange dropped a series of hints on Twitter as to the location of the cables file on the internet. He followed this up with a claim that he was now publishing new material because the Guardian had "betrayed" his password seven months earlier. Assange's claims about the Guardian were untrue.


OK so WikiLeaks redacted the files but then the whole thing went online and it was not the redacted version??? 

"Der Freitag is not just some rogue German paper: they have a syndication deal with the Guardian" http://techcrunch.com/2011/08/28/unredacted-wikileaks-cables-found-online-probably-depressingly/ 

Book in German published Jan 2011

Jan 29, 2011
"The Age of WikiLeaks" by Greg Mitchell - first WL book in english. Order now! http://www.blurb.com/bookstore/detail/1949679


1 Feb Leigh and Harding book published?? They did not protect source Manning https://wlcentral.org/node/1138 
Jan 31, 2011 https://twitter.com/wikileaks/status/31851043750936576?s=20
It should be noted, that as far as we know, neither we, nor the Guardian have any inside knowledge as to who the sources are. 


On 31 January 2011 the Guardian https://twitter.com/wikileaks/status/31850848468336640?s=20
Guardian names Manning as source. Sarah Tisdall mark 2. The slimiest media organization in the UK. http://is.gd/GT0tzF


February 2011 David Leigh of The Guardian published the encryption passphrase in a book. August 2011, German weekly Der Freitag published some of these details, enabling others to piece the information together and decrypt the Cablegate files. The cables were then available online, fully unredacted. In response, WikiLeaks decided on 1 September 2011 to publish all 251,287 unedited documents. 

WikiLeaks: Inside Julian Assange's War on Secrecy Paperback – 1 Feb 2011
by David Leigh (Author), Luke Harding (Author) https://www.amazon.co.uk/WikiLeaks-Inside-Julian-Assanges-Secrecy/dp/0852652399

Location revealed by Der Freitag 07:00 25.08.2011: https://www.freitag.de/autoren/steffen-kraft/leck-bei-wikileaks 

Domscheit-Berg in an interview with Freitag: "No, I have not taken any documents from Wikileaks. And we have no other treasure chest from which we could use ourselves. "



Feb 7 Assange full extradition case starts Belmarsh Magistrates Court http://is.gd/FQpWLh https://twitter.com/wikileaks/status/31483007625863169?s=20 


=== March 

On March 10, State Department spokesman Philip J. Crowley criticized Manning's treatment as "ridiculous, counterproductive and stupid".[184] 

President Obama, asked Friday about Crowley's statement, said he had made inquiries about the conditions of Manning's incarceration. "I have actually asked the Pentagon whether or not the procedures that have been taken in terms of his confinement are appropriate and are meeting our basic standards. They assured me that they are," Obama said. https://www.washingtonpost.com/wp-dyn/content/article/2011/03/11/AR2011031106542.html 



=== April 

2011 april tweet: Domschiet, NYT, Guardian, attempted Gitmo spoiler against our 8 group coalition. We had intel on them and published first. https://twitter.com/wikileaks/status/62365375911829505?s=20 

April 2011: Wikileaks releases the Guantanamo Files, exposing systematic and routine violations of the Geneva Conventions and abuse of 800 prisoners as young as 14 and as old as 89 at Guantanamo Bay. https://wikileaks.org/gitmo/


On April 20 the Pentagon transferred Manning to the medium-custody Midwest Joint Regional Correctional Facility, at Fort Leavenworth, Kansas, where she was placed in an 80-square-foot cell with a window and a normal mattress, able to mix with other pretrial detainees and keep personal objects in her cell.[187]



=== May 

31 May 2011 The Unknown Prisoners of Guantanamo (Part One of Ten) by Andy Worthington  https://wikileaks.org/The-Unknown-Prisoners-of.html

=== June

=== July


=== August

14 August 2011: DDB expelled from CCC https://spyblog.org.uk/ssl/wikileak/2011/08/chaos-computer-club-expels-daniel-domscheit-berg---will-this-affect-openleaksorg.html NOTE THIS IS HOSTILE

Former WikiLeaks spokesman Daniel Domscheit-Berg was expelled from the national CCC (but not the Berlin chapter) in August 2011.[30][31] This decision was revoked on February 2012.[32] As a result of his role in the expulsion, board member Andy Müller-Maguhn was not reelected for another term. 

Müller-Maguhn was criticized for his role in the CCC board's controversial decision to expel former WikiLeaks spokesman Daniel Domscheit-Berg, which was often attributed to Müller-Maguhn's close relation to Wikileaks founder Julian Assange and an ongoing conflict between Assange and Domscheit-Berg.[4] At an extraordinary general meeting in February 2012, this decision was reverted, while Müller-Maguhn was not reelected to the board.[1]

He appeared with Julian Assange on Episode 8 and 9 of The World Tomorrow, "Cypherpunks: 1/2".[5][6]

He is a contributor to Julian Assange's 2012 book Cypherpunks: Freedom and the Future of the Internet along with Jacob Appelbaum and Jérémie Zimmermann. 

August 2011, Reuters announced that Daniel Domscheit-Berg had destroyed approximately 5GB of data cache from Bank of America, that Assange had under his control.[264]

August 15th. Renata Avila see below for text 2011 statement on DDB: https://marthamitchelleffect.wordpress.com/tag/ccc/ 


=== September 

1 September 2011: Guardian journalist negligently disclosed Cablegate passwords: https://wikileaks.org/Guardian-journalist-negligently.html

1 Sept 2011 by James Ball: WikiLeaks prepares to release unredacted US cables https://www.theguardian.com/media/2011/sep/01/wikileaks-prepares-unredacted-us-cables 

> WikiLeaks is conducting an online poll of its Twitter followers to decide whether the whistleblowing site should publish in full its unredacted cache of US diplomatic cables. The site last week released more than 120,000 of its cache of diplomatic cables, with almost no redactions to protect the identity of informants and other individuals. The huge scale of the release, compared with 20,000 cables disclosed in the past nine months, prompted fierce criticism from the Australian government and former US state department spokesman PJ Crowley. WikiLeaks appeared likely to use the Twitter responses, which it said favoured disclosure at a ratio of 100 to one, to pave the way for imminent disclosure of the remaining material from its cable archive. The majority of cables published in the past week by WikiLeaks were unclassified but the site released the full archives, including confidential and secret cables, from Sweden and Australia. The Australian cables, which unlike previous releases were not apparently redacted, included a document identifying 23 Australians alleged to have links with al-Qaida, prompting an angry response from Robert McClelland, Australia's attorney general.

Fails to mention that archive is already being shared widely, discusses a second file red herring??. 

> However, at a later stage the same encrypted file and at least one other encrypted with the same password was posted on the peer-to-peer file-sharing network BitTorrent. One of these files was first published on 7 December 2010, just hours before Assange's arrest. In the days running up to his arrest, Assange had spoken of "taking precautions" in the event of anything untoward happening to him. This file, it was later discovered, was the same file that had been shared with the Guardian via the secure server. It shared the same file name and file size, and could be unlocked using the same password as that given to Leigh. Daniel Domscheit-Berg, a former member of staff at WikiLeaks who is attempting to set up a rival whistleblowing website, discovered this republished file and shared information on WikiLeaks's security breach with a small group of journalists. Avoiding the re-use of passwords and avoiding republishing temporary files are both considered basic security procedures among online security experts. However, the file was not discovered or downloaded by the public. By 10am on Thursday it had been accessed once in the previous 31 days, despite mounting speculation about its existence. Initial news stories did not give details of the location of files or of passwords. Later, WikiLeaks and some of its supporters published a series of hints about the passwords and files. At about 11pm on Wednesday an anonymous Twitter user discovered the published password and opened a separate file – not the one shared with the Guardian – that had also been circulating on file-sharing networks for several months. There was no evidence that any member of the public had sufficient information to find and decrypt the files even hours before their discovery.

1 Sept 2011: by Leigh and Ball: WikiLeaks decides to make public all US state department cables https://www.theguardian.com/media/2011/sep/01/wikileaks-make-public-all-state-cables 

> On 7 December, the day of his arrest, a huge file of WikiLeaks information was posted on the Pirate Bay filesharing site by one of his supporters. According to the group's former No 2, computer expert Daniel Domscheit-Berg: "These people said they wanted to keep WikiLeaks operational, but they never spoke to Julian." As a result, it was never apparently realised that the file-set included Assange's copy of all the classified US cables... What Assange did not reveal was that he had not followed conventional security practice and created a new password for the transaction. Instead, according to Domscheit-Berg, he had merely reused the existing master password, already known to others within WikiLeaks. "The file was never supposed to be shared with anyone at all. To get a copy you would usually make a new copy with a new password. He was too lazy to create something new." Early this year the Guardian published a book on WikiLeaks. In the course of it the password Assange had provided, assumed to be long obsolete, was published. The book contained no information that would enable anyone to find and download the encrypted file... Domscheit-Berg, who says he parted company with Assange over security concerns among other reasons, ended up alleging to a German newspaper, Freitag, that WikiLeaks was insecure. He said a file existed on the internet that contained the raw cables, and was capable of being accessed by the published password. He and Freitag took care to provide no location information that would enable the file to be accessed by any member of the public... To protests from the Australian and US governments that he was endangering sources, Assange dropped a series of hints on Twitter as to the location of the cables file on the internet. He followed this up with a claim that he was now publishing new material because the Guardian had "betrayed" his password seven months earlier. Assange's claims about the Guardian were untrue.

1 sept 2011 by James Ball: Unredacted US embassy cables available online after WikiLeaks breach https://www.theguardian.com/world/2011/sep/01/unredacted-us-embassy-cables-online 

> A Twitter user has now published a link to the full, unredacted database of embassy cables. The user is believed to have found the information after acting on hints published in several media outlets and on the WikiLeaks Twitter feed, all of which cited a member of rival whistleblowing website OpenLeaks as the original source of the tipoffs...

> WikiLeaks said it contacted the US state department on 25 August to warn that the full publication of cables may be imminent and to check whether the department's programme to notify those named in the documents had been completed. Julian Assange was said to have had a 75 minute phone conversation with Cliff Johnson, a legal advisor at the department, but was refused a face-to-face meeting to exchange further information... 

> A statement from the Guardian said: "It's nonsense to suggest the Guardian's WikiLeaks book has compromised security in any way. Our book about WikiLeaks was published last February. It contained a password, but no details of the location of the files, and we were told it was a temporary password which would expire and be deleted in a matter of hours. It was a meaningless piece of information to anyone except the person(s) who created the database. No concerns were expressed when the book was published and if anyone at WikiLeaks had thought this compromised security they have had seven months to remove the files. That they didn't do so clearly shows the problem was not caused by the Guardian's book." 

2 Sept James Ball: 
Why I felt I had to turn my back on WikiLeaks https://www.theguardian.com/media/2011/sep/02/why-i-had-to-leave-wikileaks 

> I  joined WikiLeaks last November as a staffer for a three-month stint... Julian mustered funds from celebrity backers. But trying to use WikiLeaks' precarious resources to fight a personal legal action was, to my view, morally indefensible. .. Shamir was introduced to the team under the pseudonym Adam, and it was only several weeks after he had left – with a huge cache of unredacted cables – that most of us started to find out who he was... Shamir had been seen leaving the interior ministry of Belarus, an eastern European dictatorship. The next day, the country's dictator, Alexander Lukashenko, boasted he would start a Belarusian WikiLeaks showing the US was funding his political rivals. Scores of arrests of opposition activists followed the country's elections – but Shamir wrote a piece painting an idyllic picture of free, fair, elections in a happy country...  I attempted to leave the organisation early. This was refused. I was cornered for several days and asked to sign a gagging agreement. Supporters were asked to "apply psychological pressure" to encourage me to sign, evidencing a growing cultlike ethos at the centre of the group... The final straw for me came on Friday. By drawing attention to, and then publishing in full, the unredacted cache of documents, WikiLeaks has done the cause of internet freedom – and of whistleblowers – more harm than US government crackdowns ever could.

2 Sept 2011: James Ball: Julian Assange could face arrest in Australia over unredacted cables https://www.theguardian.com/media/2011/sep/02/julian-assange-arrest-australia-wikileaks

> Australia's attorney general, Robert McClelland, confirmed in a statement on Friday that the new cable release identified at least one individual within the country's intelligence service. He added it is a criminal offence in the country to publish any information which could lead to the identification of an intelligence officer.

> The Guardian, New York Times, El País, Der Spiegel and Le Monde, who worked with WikiLeaks publishing carefully selected and redacted documents in December last year, issued a joint statement condemning the latest release. "We deplore the decision of WikiLeaks to publish the unredacted state department cables, which may put sources at risk," it said. "Our previous dealings with WikiLeaks were on the clear basis that we would only publish cables which had been subjected to a thorough joint editing and clearance process. We will continue to defend our previous collaborative publishing endeavour. We cannot defend the needless publication of the complete data – indeed, we are united in condemning it. "The decision to publish by Julian Assange was his, and his alone."


22 Sep 2011 Julian Assange autobiography: why he didn't want it published https://www.theguardian.com/media/2011/sep/22/julian-assange-memoir-argument


=== October

Was Occupy around here? 

24 October 2011 The bankers' blockade of WikiLeaks must end by James Ball https://www.theguardian.com/commentisfree/2011/oct/24/bankers-wikileaks-free-speech 

> In December 2010 three of the world's biggest payment providers, Visa, Mastercard and Paypal, cut off funding to WikiLeaks. Ten months later, Julian Assange has announced the whistleblowing site will suspend operations until the blockade is lifted – and warned WikiLeaks does not have the money to continue into 2012 at current levels of funding... WikiLeaks has not released a single file since the publication of the Guantánamo Bay material – obtained independently by the Guardian and New York Times – in April. The site's primary submissions system has been offline since Daniel Domscheit-Berg and others walked away from WikiLeaks in the summer of 2010. Assange says a replacement will be online by the end of November... Assange also claims WikiLeaks has over 100,000 documents waiting to be released – but this claim might not bear scrutiny.

=== November

Israel Shamir and Julian Assange's cult of machismo by James Ball https://www.theguardian.com/commentisfree/cifamerica/2011/nov/08/israel-shamir-julian-assange-cult-machismo

27 Nov 2011 the Walkley Foundation awarded WikiLeaks the Walkley Award for "Most outstanding contribution to journalism"
https://www.greenleft.org.au/content/assange-defiant-wikileaks-wins-journalism-award 

29 Nov 2011 James Ball: Bradley Manning treatment in custody concerns MEPs https://www.theguardian.com/world/2011/nov/29/bradley-manning-concerns-mep-letter Open letter to US authorities raises human rights fears and urges access for UN special rapporteur on torture to whistleblower... The call on the US government comes before a pre-trial hearing – Manning's first appearance in court – which begins on 16 December.  https://www.theguardian.com/world/2011/nov/29/bradley-manning-mep-open-letter 

> Manning will attend an Article 32 hearing, the US military equivalent of a pre-trial hearing, on 16 December. This is expected to last five days. Manning's lawyer, David Coombs, has indicated he wishes to call 50 witnesses at the hearing, but military authorities are considered unlikely to grant such a request.  The Article 32 hearing then makes a recommendation to a general as to whether to proceed to a full trial.

=== December

Riots in England. https://www.theguardian.com/uk/2011/dec/05/more-english-riots-to-come 

FOWL 





Renata Avila August 15th. 2011 statement on DDB: https://marthamitchelleffect.wordpress.com/tag/ccc/ 

"In May 2009 I stayed at Mr. Domscheit-Berg’s home in Wiesbaden, Germany for a week while I was visiting a research center located a few hours from his home. On arriving at Mr. Domscheit-Berg’s home, Mr. Assange had just left. Mr. Domscheit-Berg explained to me that he had only asked Mr. Assange to leave because there was not enough space for all three of us to stay in his home. During my stay, he told me that he had had a great time with Mr. Assange. He even went so far as to say it was the best time of his life. It was clear to me that he had very much enjoyed Mr. Assange’s company. He was full of admiration for Mr. Assange, saying what a pleasure it was to talk to him and that he could listen him for hours. For example, he described the time they spent in Italy, at the journalism conference in Peruggia, giving interviews and spending time with Italian colleagues as “a wonderful time”.

Before leaving I gave WikiLeaks some documents detailing proof of torture and government abuse of a Latin America country. The documents were only in hard copy. I entrusted those valuable documents – the only copy available – to Wikileaks because of the expertise of the people running it, their procedures and the mechanisms they used to maximize impact when published. I did not intend to give such material to Mr. Domscheit-Berg personally, as was made clear to him by me at the time. My intention was to give it to the platform I trusted and contributed to; to WikiLeaks. The material has not been published and I am disturbed to read public statements by Mr. Domscheit-Berg in which he states that he has not returned such documents to WikiLeaks.

Mr. Domscheit-Berg and I stayed in touch, he invited me to his wedding in mid 2010 but I was unable to attend. After his wedding, I noticed that his enthusiasm, his interest and priorities regarding WikiLeaks changed significantly. "


Inside WikiLeaks: My Time with Julian Assange at the World's Most Dangerous Website Paperback – 15 Feb 2011
by Daniel Domscheit-Berg (Author) https://www.amazon.co.uk/Inside-WikiLeaks-Assange-Dangerous-Website/dp/0224094017/ref=cm_cr_pr_product_top


 
* 

https://marthamitchelleffect.wordpress.com/

Despite WikiLeaks’ frantic requests for the press to be careful about how much they revealed,  Der Freitag,  TechCrunch and Der Spiegel all published stories based on Domscheit-Berg’s information about the cables and the passphrase.

Within days, the location was found, and every file within every directory of the data-set was checked against David Leigh’s published passphrase. The first to put all the pieces of the jigsaw together was Nigel Parry:

In the directory, date-stamped 9 June 2010, were 4 files, all encoded with Pretty Good Privacy (PGP) encoding, the files names with *.gpg suffixes. I started at the bottom of the list, putting in the David Leigh password. It unzipped z.gpg into a file called z.7z. Opening that file and extracting it using the Ez7z compression / decompression program, the file spat out a file called cables.csv, dated with a creation date of April 12, 2010 at 9:22PM. It was a 1.61GB file but it had been reported in the German press to be 1.73GB.

* 
 
MANNING: 

Her oped: https://www.theguardian.com/commentisfree/2015/may/27/anniversary-chelsea-manning-arrest-war-diaries

 January 18, 2011, after Manning had an altercation with the guards, the commander of Quantico classified her as a suicide risk.[179] Manning said the guards had begun issuing conflicting commands, such as "turn left, don't turn left," and upbraiding her for responding to commands with "yes" instead of "aye". Shortly afterward, she was placed on suicide watch, had her clothing and eyeglasses removed, and was required to remain in her cell 24 hours a day. The suicide watch was lifted on January 21 after a complaint from her lawyer, and the brig commander who ordered it was replaced.[180] On March 2, she was told that her request for removal of POI status—which entailed among other things sleeping wearing only boxer shorts—had been denied. Her lawyer said Manning joked to the guards that, if she wanted to harm herself, she could do so with her underwear or her flip-flops. The comment resulted in Manning being ordered to strip naked in her cell that night and sleep without clothing. On the following morning only, Manning stood naked for inspection. Following her lawyer's protest and media attention, Manning was issued a sleeping garment on or before March 11.[181]

The detention conditions prompted national and international concern. Juan E. Méndez, United Nations Special Rapporteur on torture, told The Guardian that the U.S. government's treatment of Manning was "cruel, inhuman and degrading".[182] In January 2011 Amnesty International asked the British government to intervene because of Manning's status as a British citizen by descent, although Manning's lawyer said Manning did not regard herself as a British citizen.[183] On March 10, State Department spokesman Philip J. Crowley criticized Manning's treatment as "ridiculous, counterproductive and stupid".[184] The following day, President Obama responded to Crowley's comments, saying the Pentagon had assured him that Manning's treatment was "appropriate and meet[s] our basic standards". Under political pressure, Crowley resigned three days after his comments.[185] On March 15, 295 members of the academic legal community signed a statement arguing that Manning was being subjected to "degrading and inhumane pretrial punishment" and criticizing Obama's comments.[186] On April 20 the Pentagon transferred Manning to the medium-custody Midwest Joint Regional Correctional Facility, at Fort Leavenworth, Kansas, where she was placed in an 80-square-foot cell with a window and a normal mattress, able to mix with other pretrial detainees and keep personal objects in her cell.[187]
Evidence presented at Article 32 hearing
In April 2011, a panel of experts, having completed a medical and mental evaluation of Manning, ruled that she was fit to stand trial.[188] An Article 32 hearing, presided over by Lieutenant Colonel Paul Almanza, was convened on December 16, 2011, at Fort Meade, Maryland; the hearing resulted in Almanza's recommending that Manning be referred to a general court-martial. She was arraigned on February 23, 2012, and declined to enter a plea.

* 


24 December 2010 Glenn Greenwald: What WikiLeaks revealed to the world in 2010 https://web.archive.org/web/20111229060845/http://www.salon.com/2010/12/24/wikileaks_23/

> As revealing as the disclosures themselves are, the reactions to them have been equally revealing.  The vast bulk of the outrage has been devoted not to the crimes that have been exposed but rather to those who exposed them:  WikiLeaks and (allegedly) Bradley Manning.  A consensus quickly emerged in the political and media class that they are Evil Villains who must be severely punished, while those responsible for the acts they revealed are guilty of nothing.  
