

== 2012: 


Jan 1, 2012 https://twitter.com/wikileaks/status/153439639397613568?s=20
2012: Assange: 390 days detained without charge, WikiLeaks: 393 days bank blockade, Manning 587 days military jail

Jan 1, 2012 https://twitter.com/wikileaks/status/153121522746265600?s=20
Friends of WikiLeaks is nearing critical mass. 3k more members and we press the red button https://wlfriends.org

27 Feb 2012: James Ball: WikiLeaks releases first 200 of 5m Stratfor emails https://www.theguardian.com/media/2012/feb/27/wikileaks-stratfor-emails-anonymous

> The emails originated not from a whistleblower, but instead from a series of hacking attacks against Stratfor in December 2011, carried out by the online activist collective Anonymous. Anonymous apparently passed the emails to WikiLeaks in the weeks following the attack. The whistleblowing website then recruited, according to its statement, 25 media partners to work on the document cache...

> "The material contains privileged information about the US government's attacks against Julian Assange and WikiLeaks and Stratfor's own attempts to subvert WikiLeaks," the whistleblower website said. "There are more than 4,000 emails mentioning WikiLeaks or Julian Assange. The emails also expose the revolving door that operates in private intelligence companies in the United States."

> Emails between the founder and Karl Rove, a senior advisor to George Bush, are among those released to date. The cache also contains gossip between Stratfor staff, apparently originating from the 2008 presidential campaign of John McCain, that the senator was encouraged to take action against President Obama for alleged electoral fraud in two states. Coca-Cola also seemingly engage Stratfor for background research against Peta activists in Canada ahead of the Vancouver Winter Olympics in 2010.... One of the largest Anonymous-linked accounts on Twitter, @AnonymousIRC, put out a series of tweets within minutes seemingly confirming it was the source of the WikiLeaks release.

March 2012: Assange announced that he would run for the Australian Senate under the new WikiLeaks Party,[142][143] and Cypherpunks[144] was published in November. In 2012, Assange hosted a television show on RT, a network funded by the Russian government.[145] In the same year, he analysed the Kissinger cables held at the US National Archives and released them in searchable form


March 2012: New Statesman article on Shamir and Lukachenko https://www.newstatesman.com/blogs/the-staggers/2012/03/belarus-assange-lukashenko 

19 June 2012 James Ball: WikiLeaks cables paint chequered picture of Ecuador https://www.theguardian.com/world/2012/jun/19/wikileaks-cables-ecuador-julian-assange 

> A 2009 cable noted with concern a series of moves made by President Correa against commercial media in the country since he came into office. 

20 June 2012: James Ball: Julian Assange's drama: in the third act, we still don't know what the story is (says there is "no evidence" to support "theory" US is after JA, despite Stratfor email above) https://www.theguardian.com/media/2012/jun/20/julian-assange-drama-third-act 

> Sixteen supporters who allegedly took part in attacks on PayPal, Mastercard and Visa, the online equivalent of sit-in protests, for their boycott of WikiLeaks each face up to 15 years in prison and await their day in court. A group of alleged UK hackers belonging to the Lulzsec group will each face their trials next week. And the WikiLeaks submission system remains down, as it has for nearly two years.

24 August 2012: Who is Julian Assange? By the people who know him best. by James Ball, Alan Rusbridger, Heather Brooke, John Pilger, Mark Stephens, Ken Loach and Ian Katz. 

Mention the logo history? Mole v hourglass

* 

2013

9 April 2013: Do we need WikiLeaks any more? by James Ball https://www.theguardian.com/commentisfree/2013/apr/09/do-we-need-wikileaks 

WikiLeaks published Kissinger Cables. WikiLeaks describes its trove as “the single most significant body of geopolitical material ever published”.

> There has been no way to submit material to an online dropbox run by WikiLeaks since 2010... A modern media that is willing to collaborate across borders, throw dozens of bodies at months-long investigations and learn how to handle safely gigabytes of data, could in the long run – if it sustains – be WikiLeaks greatest, if accidental, achievement. 

== 2014

https://www.businessinsider.com.au/wikileaks-and-edward-snowden-2014-1

At the Chaos Computer Club conference on Dec. 29, Assange said that “WikiLeaks was able to rescue Edward Snowden because we are an organised institution with collective experience.”

Top WikiLeaks adviser Sarah Harrison, who met Snowden in Hong Kong and accompanied him to Moscow, then asked the last question coming from the Internet:

    “What was the most difficult part on getting Snowden out of the U.S.?” 

Assange, Harrison and “American WikiLeaks Hacker” Jacob Appelbaum all laughed, and then Appelbaum said: “That’s quite a loaded question.”

Assange then said: “Yeah, that’s interesting to think whether we can actually answer that question at all. I’ll give a variant of the answer because of the legal situation it is a little bit difficult.”

* 

== 2015

2015 Assange writes to President of France: https://www.lemonde.fr/idees/article/2015/07/03/julian-assange-monsieur-hollande-accueillez-moi-en-france_4668919_3232.html 


* 


2012

June: Julian seeks political asylum at the Ecuadorean Embassy in London, days after the Supreme Court rejects the last of his appeals against extradition to Sweden. Julian and supporters argue that his removal to Sweden would be followed by a potential extradition to the US, likely on Espionage Act charges, where he could face the death penalty. On 19 June 2012, Ecuadorian Foreign Minister Ricardo Patiño announces that Julian has applied for political asylum, that his government is considering the request, and that Julian is at the Ecuadorian Embassy in London.

August: Ecuador invokes international law in recognising the political persecution of Julian and grants him the status of political refugee, judging his life to be at grave risk. Ecuador’s decision is backed by the Union of South American Nations countries and ALBA.

July: The Syria Files are published, providing an extraordinary insight into the Assad government through over two million emails from 680 Syrian political figures, ministries and associated companies and the regime’s international security contracts.

December: A court ruling finds that the US treatment of Khaled El-Masri amounts to torture and that he had been effectively disappeared by the US and Macedonian authorities. El-Masri, a Lebanese-born German citizen, was seized in Macedonia in 2003, transferred to Kabul as part of the US “Extraordinary Rendition” program and detained for four months before being released without any charges on a roadside in Albania. He took his case to the European Court of Human Rights, using six cables released by WikiLeaks in evidence.
2013

Major trade agreements TPP, TTIP & TISA – drafted and negotiated in secret without proper democratic oversight – are made public when WikiLeaks publishes multiple draft chapters and negotiating positions, fueling social justice and fair trade movements. The documents are published in multiple releases over 2013, 2015 and 2016. The Trans Pacific Partnership Agreement (TPP) and Transatlantic Trade and Investment Partnership (TTIP) are now stalled, while Trade in Service Agreement (TiSA) remains classified.

2015

June: The Saudi foreign ministry files, passed to WikiLeaks, reveal, among other things, that Britain conducted secret vote-trading deals with Saudi Arabia to ensure both states were elected to the UN human rights council.

July: The NSA World Leaders Targets: a number of releases in July 2015 and February 2016, documenting NSA targets, including UN Secretary General Ban Ki-Moon’s meetings with Heads of State, Chancellor Merkel, Prime Ministers Berlusconi and Netanyahu, President Hollande, the Japanese cabinet, UNHCR and WTO officials.
2016

February: Central African Republic mining files reveal mining operations conducted by Western and Chinese companies in the CAR that escape responsibility for environmental consequences. The files contain detailed maps of mining rights, mining contracts with illegal kickbacks and secret investigative reports.

The United Nations Working Group on Arbitrary Detention concludes in a published report that Julian has been subject to arbitrary detention by the UK and Swedish governments since 7 December 2010, including his time in prison on conditional bail and in the Ecuadorian embassy, and that he was “entitled to his freedom of movement and to compensation.”

July: The Democratic National Committee Leaks consist of 19,252 emails and 8,034 attachments from the US Democratic National Party leadership, which result in the resignation of five top officials who had stacked the deck against one of the two Democratic candidates, Bernie Sanders, to favour Hillary Clinton.

November: After receiving criticism from other Swedish law practitioners, the Swedish prosecutor, haing finally agreed to interrogate Julian in the Ecuadorian Embassy in London, begins interviews on 14 November 2016.

December: WikiLeaks releases 2,420 documents originating from various agencies of the German government, including the BND and Federal Office for the Protection of the Constitution.

2017

March: WikiLeaks begins publishing Vault 7, detailing activities and capabilities of the US Central Intelligence Agency (CIA) to perform electronic surveillance and cyber warfare. The files include details on the scope and direction of the CIA’s global covert hacking program, its malware arsenal and software capabilities, such as the ability to compromise cars, smart TVs, web browsers and operating systems of most smartphones, including products such as Apple’s iPhone, Google’s Android and Microsoft’s Windows and even Samsung TVs, which can be turned into covert microphones.

April: CIA Director Mike Pompeo calls WikiLeaks a “hostile intelligence service” and says “we can no longer allow Assange and his colleagues the latitude to use free speech values against us.”

May: The Swedish authorities drop their investigation against Julian. However he still faces arrest if he leaves the Embassy building in Knightsbridge, London, for breaching his former bail conditions in the UK when he entered Ecuadorian Embassy.

September: The Russia Spy files begin to be released in September 2017, consisting of over 650,000 critical documents relating to Russia under Vladimir Putin, including releases about surveillance contractors in Russia.

October: CIA director Mike Pompeo further describes Wikileaks as an “enormous threat” and states that the US is “working to take down” the organisation.

December: Julian is granted Ecuadorian citizenship.

2018

January: As Julian’s health deteriorates, doctors examining him call for him to be granted safe passage to hospital.

February: A UK judge rules that the arrest warrant against Julian should be maintained, meaning that he continues to face arrest if he leaves the Ecuadorian Embassy. The ruling comes a day after it was revealed that Swedish prosecutors attempted to close their investigation in 2013, but British prosecutors dissuaded them from doing so.

March: the new government in Ecuador unilaterally imposes new conditions on Julian that prevent him from having visitors and receiving telephone calls and other electronic communications, permitting him only to meet with his lawyers. Numerous public figures issue statements in support of Julian, calling for Ecuador to #ReconnectJulian and end his isolation. At least four open letters from civil society advocates around the world are sent to the Ecuadorian government, calling for an end to Julian’s isolation conditions. More than 87,000 supporters signed a petition launched by Brian Eno and Yanis Varoufakis, hosted by DiEM25.

It is later revealed that on 8 March 2018, the “process of moving Assange out of the Ecuadorian Embassy” began when “the Ecuadorians made their first request to the U.K.: a letter asking for written assurances that the U.K. would not extradite Assange to a country where he could face the death penalty, according to the Ecuadorian Interior Minister Maria Paula Romo.”

Ecuador’s move to cut off Julian’s communications occurs one day after a high level US military visit to Ecuador “to discuss security cooperation”.

April: The US and Ecuador sign a new military cooperation agreement.

The Democratic National Committee files a lawsuit against the Russian government, the Trump campaign, and various individuals it alleges participated in the plot to hack its email servers and disseminate the contents during the 2016 election. The DNC also sues WikiLeaks for its role in publishing the hacked materials, though it does not allege that WikiLeaks participated in the hacking or knew about it in advance; its sole role, according to the DNC’s lawsuit, was publishing the hacked emails. According to journalists Glenn Greenwald and Trevor Timm, writing for The Intercept, the DNC lawsuit poses a serious threat to media freedom in the US.

May: Reports about Julian’s stay in Ecuadorian embassy being in jeopardy mount. CNN reports that the situation has become “unusually bad” and that Julian’s refuge in the embassy may end “any day now.”

A ruling from the Inter-American Court on Human Rights ruled that states granting asylum must provide safe passage to asylees in embassies, in effect setting out Ecuador’s obligations in relation to Julian.

June: US Vice President Mike Pence visits Ecuador, where the case of Julian Assange is raised in a meeting with Ecuadorian President Lenin Moreno. Before his visit, ten Democratic Senators send a letter to Pence urging him to address the issue “at a time when Wikileaks continues its efforts to undermine democratic processes globally”.

July: Media reports suggest that the UK and Ecuador are seeking to reach a “high level” agreement to breach Julian’s asylum by handing him over to the UK police to be arrested.

September: Ecuador’s ambassador to Germany, Manuel Mejia Dalmau,”sought a private ’emergency meeting’ in Berlin with the U.S. Ambassador to Germany, Richard Grenell, viewed as one of President Donald Trump’s closest envoys in Europe,” said to mark Ecuador’s “direct outreach” to the US on Assange.

October: Ecuador unilaterally imposes further restrictions on Julian in a new “Protocol”. This includes explicit threats to revoke Julian’s asylum if he, or any visitors, breach or are perceived to breach, any of the 28 “rules” in the protocol. The “protocol” forbids Julian from undertaking journalism and expressing his opinions, under threat of losing his asylum. The rules also state that the embassy can seize Julian’s property or his visitors’ property and hand these to the UK police, and report visitors to the UK authorities.

November: US prosecutors inadvertently reveal that Julian has been charged under seal (i.e., confidentially) in the US – something which WikiLeaks and others long claimed. The document making the admission was written by Assistant US Attorney Kellen S Dwyer. The Wall Street Journal reports that “over the past year, US prosecutors have discussed several types of charges they could potentially bring against Mr. Assange”. It notes that charges against Julian could include violating the US Espionage Act, which criminalises releasing information regarding US national defence.

The Guardian publishes fabricated claim that Paul Manafort visited Assange in the Embassy in 2016. Six US Congressmen publish letter to Sec. Mike Pompeo concerning his 26 November meeting with Foreign Minister of Ecuador, specifically referencing Manafort allegation.

2019

January: US interrogates Ecuadorian diplomats, obtains documents, on pretext of fabricated Manafort-Assange meeting,

February: Ecuador inks $4.2 billion financing deal with IMF. Chelsea Manning reveals subpoena to testify to WikiLeaks grand jury.

March: Chelsea Manning imprisoned for refusing to testify in WikiLeaks grand jury investigation. Met Police admits it collaborated with US prosecutors since at least 2013 in WikiLeaks investigation.

April: Ecuador twists embarrassing INA Papers into pretext to oust Assange. UN torture expert Nils Melzner urges Ecuador not to expel Assange from embassy.

WikiLeaks uncovers spying operation on Assange. On 11 April 2019, Ecuador illegally revokes asylum and lets British police into the Embassy, and Julian Assange is arrested, as a US extradition request and indictment are unsealed. Days later, FBI Agent’s Affidavit in support of Assange arrest is unsealed.

May: United Nations Working Group on Arbitrary Detention expresses concern about Assange proceedings. Sweden reopens investigation into Julian Assange, seeks to extradite. US and Ecuador sign new agreement after Assange expelled, and subsequently Ecuador hands over Assange’s entire legal defense to the United States.

Julian Assange charged under 17 Espionage Act counts in superseding indictment.

UN torture expert: “collective persecution” of Julian Assange must end now.

June: Swedish court blocks Swedish extradition from UK for time being, rejects prosecutor’s detention request for Julian Assange.

UN torture expert:

    ‘Demasking the Torture of Julian Assange’
    UN torture expert says Assange’s persecution ‘very similar to historic witch-hunts’
    UN Torture Expert Says Assange Is Victim of Psychological Torture

Report: Julian Assange won’t face further charges in US

Brief: Media analysis of Julian Assange’s superseding indictment

News: U.S. delivers formal extradition request for Julian Assange to U.K.

Extradition hearing: At Julian Assange’s extradition hearing today at Westminster Magistrates’ Court in London, which Assange attended via videolink from HMP Belmarsh, the full substantive proceedings were scheduled for five days in February 2020. Assange will also have a hearing in October this year.

DOJ tells Chelsea Manning it is investigating others in addition to Assange.

MEPs urge Commission to halt Assange extradition to US.

July: EL PAÍS: Spanish security company spied on Julian Assange’s meetings with lawyers

Chelsea Manning’s lawyer refutes conspiracy allegation against Julian Assange.

UN Special Rapporteur on Torture Nils Melzer sends letters to the governments of the United States, United Kingdom, Ecuador and Sweden to express that he is “gravely concerned” about Assange’s treatment and to urge the latter three governments to ensure Assange is not extradited to the United States.

The DNC’s lawsuit against WikiLeaks is dismissed, with the judge noting that the publication of the DNC emails “is plainly of the type entitled to the strongest protection that the First Amendment offers.”

August: Former Consul to Ecuador in UK: 40 Rebuttals to CNN’s Bias on Assange

September: Julian Assange wins Compassion in Care’s 2019 Gavin MacFadyen Award for Whistleblowers.

Imprisoned activist Jeremy Hammond called against his will to testify before federal Grand Jury in the EDVA, likely against Assange and WikiLeaks.


20 June 2012 Assange felt 'abandoned' by Australian government after letter from Roxon https://web.archive.org/web/20181119201315/https://www.smh.com.au/politics/federal/assange-felt-abandoned-by-australian-government-after-letter-from-roxon-20120620-20npj.html 
