= WikiLeaks: A True History

By Gary Lord

== Author's Note

This book establishes an accurate historical record of the WikiLeaks publishing organisation, established by Julian Assange in 2006. It also exposes the relentless global campaign to destroy WikiLeaks and Assange by any means possible, including financial bullying, media lies, judicial abuse of due process, intrusive surveillance, and state-sponsored disinformation campaigns.

The Internet is still young, but our online histories are already being buried and destroyed. As Internet pages replace printed sources of truth, our true histories become ever more susceptible to malicious revisionism.

Money dictates which information is displayed most prominently, with search results increasingly politicized by corporate and government agendas. Older and more valuable information slowly disappears, with independent sources under-funded, and even large media organisations don't bother publicly archiving data. 

Meanwhile opportunists have turned a tidy profit from widely publicised but error-filled books and movies about WikiLeaks, with media partners amplifying their errors and distortions. Networks of social media trolls, many with links to political parties or spy agencies, have spread minsinformation via co-ordinated PsyOps (psychological operations) campaigns. The Wikipedia pages for WikiLeaks and its founder Julian Assange have been particularly unreliable for many years, with ideologically motivated editors shutting out those who try to correct the record. 

Faced with such a barrage of misinformation, WikiLeaks has carried on publishing and let their work speak for itself. With over 10 million documents published in their first ten years, they have maintained a record of verifiable information no other major media organisation can match. Julian Assange and other WikiLeaks staff and supporters have also published books about Google, the Cypherpunks movement, and other aligned topics. But there has never been a concerted effort to document the true history of WikiLeaks itself. This book seeks to fill that gap. 

====
[NOTE]
The aborted "unofficial" biography of Julian Assange by Andrew O'Hagan is a good example of what NOT to do. After falling out with Assange, O'Hagan admitted his book had a "voice which was as invented as anything I’d ever produced in fiction." Before canceling the project, Assange told him: "People think you’re helping me write my book, but actually I’m helping you write your novel." Assange said the published version was full of errors. It has not been used as a source for this book.
====

In writing this book, considerable effort has been expended in trying to divine the truth where multiple contradictory versions of events exist. It is important to understand the reasons behind such conflicting stories: 

- Due to the nature of their work, WikiLeaks has frequently needed to operate secretively in order to avoid infiltration, protect sources, verify leaks, and thus be able to publish highly sensitive information with maximum impact. 
- Due to threats, Julian Assange, his family, colleagues, partners and sources have often been compelled to keep identities, personal information, and locations secret. 
- Many WikiLeaks critics have their own motivations for spreading lies, whether they be disgruntled former supporters trying to protect their own reputations, corporate media organisations trying to spin a profit from sensationalized headlines, or government agencies trying to spread damaging misinformation.

This book examines the major controversies created by conflicting narratives, but does not seek to catalogue the endless stream of lies, smears and conspiracy theories posted daily on social media over many years. Nevertheless it is worth noting that such a widespread campaign of hatred and lies has been sustained for so long: it says a lot about the impact of WikiLeaks releases, and how desperate certain people have been to destroy Assange's credibility, alienate public support, and shut WikiLeaks down. 

*

Continue to link:ch1.html[Chapter One] or return link:index.html[Home]. 

Please link:https://www.gofundme.com/f/wikileaks-true-history-book[support the writing of this book]. Thank you.

* 

Copyright Gary Lord 2019
